#include <macro.h>
/*
	Master Life Configuration File
	This file is to setup variables for the client, there are still other configuration files in the system

*****************************
****** Backend Variables *****
*****************************
*/
player setVariable ["playerHealth", 0, true];
player setVariable ["udcLevel",false,true];
player setVariable ["dojLevel",false,true];
player setVariable ["sosActive",false,true];
player setVariable ["isHirntod",false,true];
myHealth = 0;
Fishing_Active = false;
shooting_death = false;
bite = false;
tryingCall = false;
phonesRinging = false;
life_quitRecently = false;
phoneDisabled = false;
myCallOwner = player;
myPhoneCall = 0;
damageChance = false;
dispatch = false;
trucking = false;
dispatch2 = false;
callInProgress = false;
noleftclick = false;
allowanims = true;
harvesting = false;
isdragging = false;
im_hunting = false;
progress_bj = false;
buy_off = false;
buying_virt_item = false;
buying_phys_item = false;
allow_sat = true;
maintenance_on = false;
phone_s_1 = false;
phone_s_2 = false;
phone_s_3 = false;
previewing_on = false;
has_job = false;
driver_test = false;
start_up = true;
checked_taxi = false;
message1_active = false;
message2_active = false;
message3_active = false;
message4_active = false;
message5_active = false;
message6_active = false;
raceDone = false;
life_rebelbadguyman = false;
life_query_time = time;
life_lastKnownPos = [0,0,0];
life_show_actions = false;
life_actions = [];
skip_all = false;
im_dead = false;
life_isdowned = false;
life_action_time = 0;
life_racing = false;
cheap_buffs = false;
life_crazy = 0;
life_cokeaddict = false;
message_active = 0;
target_licenses = "None";
usingvehicle = false;
target_houses = [];
life_cruise = false;
life_charged = false;
life_gopro = false;
life_racers = [];
koil_antispam = 0;
life_newsJobs = false;
life_bankteller = false;
life_action_delay = time;
life_damagereturn = false;
life_trunk_vehicle = Objnull;
life_session_completed = false;
life_garage_store = false;
life_session_tries = 0;
life_net_dropped = false;
life_hit_explosive = false;
life_taxi = false;
life_seatbelt = false;
life_seatwarn = false;
life_smoking = false;
life_bonging = false;
paid_recently = false;
life_siren_active = false;
life_clothing_filter = 0;
life_hungerpain = false;
life_antispamactive = false;
life_koil_race = 0;
life_koil_race2 = 0;
life_rip = 0;
life_ApplyAir = false;
prevent_loot = false;
life_nos_active = 2;
life_dontsell = 0;
life_clothing_uniform = -1;
life_koil_rally = 0;
life_redgull_effect = time;
life_is_processing = false;
life_bail_paid = false;
life_nos_count = 0;
life_impound_inuse = false;
life_action_inUse = false;
life_sickness = false; 
life_paintball = false;
life_spikestrip = ObjNull;
life_deathpos = 1;
//life_respawn_timer = 9; //Scaled in minutes
life_knockout = false;
life_rope = 1;
koil_life = 1;
life_stretcher = 1;
hacking = false;
life_poop = 15;
life_std = 0;
life_maxweightdone = 0;
life_eattotal = 0;
life_dirt = 0;
life_bro = 0;
life_num = 0;
life_pizza = 0;
life_koil_parachute = 0;
life_applypressure = 0;
life_interrupted = false;
life_respawned = false;
life_removeWanted = false;
life_fadeSound = false;
life_spam_my_dick2 = 0;
life_spam_my_dick = 0;
life_married = "";
life_siren_on = 0;
koil_altcheck = false;
koildeb = 1;
koildebi = 1;
koildebii = 1;
koildebiii = 1;
koildebiiii = 1;
life_breakouton = 1;
life_nospampls = 0;
life_firing_range = false;
life_signedIn = false;
life_pickup_open = false;
life_injuries = ["diseaseon","bleedingon","woundedon","fractureon","unconciouson"];
life_carSalesman = false;
life_onTestDrive = false;
life_requestingTestDrive = false;
life_testDriveRequests = [];
PRPG_trackedVeh = 0;
PRPG_leitstelle	= false;
life_unconscious = false;

//Persistent Saving
__CONST__(life_save_civ,TRUE); //Save weapons for civs?
__CONST__(life_save_yinv,TRUE); //Save Y-Inventory for civs and cops? (Medics excluded for now)

//Revive constant variables.
__CONST__(life_revive_cops,FALSE); //Set to false if you don't want cops to be able to revive downed players.
__CONST__(life_revive_fee,500); //Fee for players to pay when revived.

//House Limit
__CONST__(life_houseLimit,3); //Maximum amount of houses a player can buy (TODO: Make Tiered licenses).

//Gang related stuff?
__CONST__(life_gangPrice,75000); //Price for creating a gang (They're all persistent so keep it high to avoid 345345345 gangs).
__CONST__(life_gangUpgradeBase,10000); //MASDASDASD
__CONST__(life_gangUpgradeMultipler,2.5); //BLAH

//Uniform price (0),Hat Price (1),Glasses Price (2),Vest Price (3),Backpack Price (4)
life_clothing_purchase = [-1,-1,-1,-1,-1];
/*
*****************************
****** Weight Variables *****
*****************************
*/
life_maxWeight = 24; //Identifies the max carrying weight (gets adjusted throughout game when wearing different types of clothing).
life_maxWeightT = 24; //Static variable representing the players max carrying weight on start.
life_carryWeight = 0; //Represents the players current inventory weight (MUST START AT 0).

/*
*****************************
****** Life Variables *******
*****************************
*/
life_net_dropped = false;
life_hit_explosive = false;
life_siren_active = false;
life_bank_fail = false;
life_use_atm = true;
life_is_arrested = false;
life_delivery_in_progress = false;
life_action_in_use = false;
life_thirst = 100;
life_battery = 75;
life_gift_recent = false;
life_charging = 2;
life_koil_hh = 2;
life_hunger = 100;
life_revivemoney = false;
life_intox = 0.00;
__CONST__(life_paycheck_period,10); //Five minutes
cash_in_hand = 0;
__CONST__(life_impound_car,835);
__CONST__(life_impound_boat,825);
__CONST__(life_impound_air,885);
life_istazed = false;
life_my_gang = ObjNull;

life_vehicles = [];
life_impoundedvehicles = [];
bank_robber = [];
switch (playerSide) do
{
	case west: 
	{
		cash_in_bank = 12000; //Starting Bank Money
		life_paycheck = 2500; //Paycheck Amount
	};
	case civilian: 
	{
		cash_in_bank = 12000; //Starting Bank Money
		life_paycheck = 1000; //Paycheck Amount
	};
	
	case independent: {
		cash_in_bank = 12000;
		life_paycheck = 2500;
	};
	case east:
	{
		cash_in_bank = 12000; //Starting Bank Money
		life_paycheck = 400; //Paycheck Amount
	};
};

/*
	Master Array of items?
*/
life_vShop_rentalOnly = ["B_MRAP_01_hmg_F","B_G_Offroad_01_armed_F","Jonzie_Quattroporte","Jonzie_30CSL","Jonzie_Viper","Jonzie_Datsun_Z432","Jonzie_STI","Jonzie_Escalade","Jonzie_Datsun_510","Jonzie_Ceed","Jonzie_Raptor","Jonzie_Galant","Jonzie_Corolla","Jonzie_Mini_Cooper","Jonzie_Mini_Cooper_R_spec","Jonzie_XB","Jonzie_VE","Jonzie_Ute"];
//,"Jonzie_Transit","Jonzie_Flat_Bed","Jonzie_Log_Truck","Jonzie_Box_Truck","Jonzie_Tanker_Truck"
__CONST__(life_vShop_rentalOnly,life_vShop_rentalOnly); //These vehicles can neve%r be bought and only 'rented'. Used as a balancer & money sink. If you want your server to be chaotic then fine.. Remove it..

life_inv_items = 
[
	"life_inv_nos",
	"life_inv_condom",
	"life_inv_medkit",
	"life_inv_cleankit",
	"life_inv_weddingring",
	"life_inv_bandage",
	"life_inv_airkit",
	"life_inv_tierope",
	"life_inv_stitches",
	"life_inv_splint",
	"life_inv_mobilephone",
	"life_inv_panicbutton",
	"life_inv_epipen",
	"life_inv_bec",
	"life_inv_MDMAu",
	"life_inv_MDMAp",
	"life_inv_methu",
	"life_inv_emerald",
	"life_inv_sapphire",
	"life_inv_ruby",
	"life_inv_methp",
	"life_inv_cokeu",
	"life_inv_cokep",
	"life_inv_oilu",
	"life_inv_oilp",
	"life_inv_heroinu",
	"life_inv_heroinp",
	"life_inv_marijuana",
	"life_inv_apple",
	"life_inv_rabbit",
	"life_inv_salema",
	"life_inv_ornate",
	"life_inv_mackerel",
	"life_inv_tuna",
	"life_inv_mullet",
	"life_inv_catshark",
	"life_inv_turtle",
	"life_inv_fishingpoles",
	"life_inv_water",
	"life_inv_donuts",
	"life_inv_turtlesoup",
	"life_inv_coffee",
	"life_inv_fuelF",
	"life_inv_fuelE",
	"life_inv_pickaxe",
	"life_inv_copperore",
	"life_inv_ironore",
	"life_inv_ironr",
	"life_inv_copperr",
	"life_inv_sand",
	"life_inv_salt",
	"life_inv_saltr",
	"life_inv_glass",
	"life_inv_tbacon",
	"life_inv_lockpick",
	"life_inv_redgull",
	"life_inv_peach",
	"life_inv_diamond",
	"life_inv_diamondr",
	"life_inv_spikeStrip",
	"life_inv_rock",
	"life_inv_cement",
	"life_inv_goldbar",
	"life_inv_blastingcharge",
	"life_inv_hackingtool",
	"life_inv_boltcutter",
	"life_inv_defusekit",
	"life_inv_storagesmall",
	"life_inv_storagebig",
	"life_inv_wheat",
	"life_inv_sunflower",
	"life_inv_corn",
	"life_inv_bean",
	"life_inv_cotton",
	"life_inv_olive",
	"life_inv_opium",
	"life_inv_cannabis",
	"life_inv_pumpkin",
	"life_inv_wheatseeds",
	"life_inv_sunflowerseeds",
	"life_inv_cornseeds",
	"life_inv_beanseeds",
	"life_inv_cottonseeds",
	"life_inv_oliveseeds",
	"life_inv_opiumseeds",
	"life_inv_cannabisseeds",
	"life_inv_pumpkinseeds",
	"life_inv_rawgoatmeat",
	"life_inv_rawchicken",
	"life_inv_rawsheepmeat",
	"life_inv_rawrabbit",
	//Additions
	"life_inv_zoobeer", // Duff Beer
	"life_inv_RoadCone",
	"life_inv_RoadConeStrip",
	"life_inv_RoadConeB",
	"life_inv_RoadConeStripB",
	"life_inv_RoadBlockWood",
	"life_inv_RoadBlockConc",
	"life_inv_RoadBlockRebel",
	"life_inv_BarGate",
	"life_inv_ziptie",
	"life_inv_tobacco",
	"life_inv_cigarette",
	"life_inv_kidney",
	"life_inv_zoobeer2",
	"life_inv_jackdaniels",
	"life_inv_vodka",
	"life_inv_jagerbomb",
	"life_inv_absinthe",
	"life_inv_redwine",
	"life_inv_whitewine",
	"life_inv_whiterussian",
	"life_inv_sexonthebeach",
	"life_inv_tequila",
	"life_inv_jackdanielsandcoke",
	"life_inv_raxsrum",
	"life_inv_blaulicht",
	"life_inv_tracker",
	
	"life_inv_silberu",
	"life_inv_silberp",
	"life_inv_titanu",
	"life_inv_titanp",
	"life_inv_gummiu",
	"life_inv_gummip",
	"life_inv_kroku",
	"life_inv_krokp",
	
	"life_inv_aluu",
	"life_inv_alup",
	"life_inv_bleiu",
	"life_inv_bleip",
	"life_inv_zinku",
	"life_inv_zinkp",
	"life_inv_lithiumu",
	"life_inv_lithiump",
	
];




//Setup variable inv vars.
{missionNamespace setVariable[_x,0];} foreach life_inv_items;
//Licenses [license var, civ/cop]
life_licenses =
[
	//Civilian Licenses
	["license_civ_MDMA","civ"],
	["license_civ_meth","civ"],
	["license_civ_coke","civ"],
	["license_civ_driver","civ"],
	["license_civ_air","civ"],
	["license_civ_heroin","civ"],
	["license_civ_marijuana","civ"],
	["license_civ_gang","civ"],
	["license_civ_boat","civ"],
	["license_civ_oil","civ"],
	["license_civ_dive","civ"],
	["license_civ_truck","civ"],
	["license_civ_gun","civ"],
	["license_civ_rebel","civ"],
	["license_civ_diamond","civ"],
	["license_civ_copper","civ"],
	["license_civ_iron","civ"],
	["license_civ_sand","civ"],
	["license_civ_salt","civ"],
	["license_civ_cement","civ"],
	["license_civ_home","civ"],
	["license_civ_udc","civ"],
	["license_civ_rifle","civ"],
	["license_civ_doj","civ"],
	["license_civ_silber","civ"],
	["license_civ_titan","civ"],
	["license_civ_gummi","civ"],
	["license_civ_krok","civ"],
	["license_civ_lcn","civ"],
	["license_civ_udclang","civ"],
	
	//RFA Licenses
	["license_med_air","med"],
	
	//Cop Licenses
	["license_cop_air","cop"],
	["license_cop_swat","cop"],
	["license_cop_cg","cop"],
	["license_cop_sert","cop"]
];

//Setup License Variables
{missionNamespace setVariable[(_x select 0),false];} foreach life_licenses;

//life_dp_points = ["dp_1","dp_2","dp_3","dp_4","dp_5","dp_6","dp_7","dp_8","dp_9","dp_10","dp_11","dp_12","dp_13","dp_14","dp_15","dp_15","dp_16","dp_17","dp_18","dp_19","dp_20","dp_21","dp_22","dp_23","dp_24","dp_25"];
//[shortVar,reward]
life_illegal_items = [["heroinu",270],["heroinp",435],["cokeu",210],["cokep",800],["cannabis",250],["opium",250],["marijuana",300],["turtle",500],["hackingtool",1000],["blastingcharge",1000],["boltcutter",350],["methu",40],["methp",400],["kroku",500],["krokp",700],["cokeu",40],["cokep",500],["MDMAu",100],["emerald",1220],["sapphire",1520],["ruby",720],["MDMAp",820]];


/*
	Sell / buy arrays
*/
sell_array = 
[
	["weddingring",80],
	["bec",1],
	["medkit",5],
	["cleankit",1],
	["mobilephone",1],
	["panicbutton",1],
	["MDMAu",100],
	["MDMAp",610],
	["emerald",1020],
	["sapphire",1020],
	["ruby",1070],
	["methu",110],
	["methp",550],
	["cokeu",210],
	["cokep",640],
	["apple",3],
	["heroinu",270],
	["heroinp",550],
	["salema",210],
	["ornate",210],
	["mackerel",140],
	["tuna",210],
	["mullet",130],
	["catshark",240],
	["marijuana",550],
	["turtle",410],
	["rabbit",3],
	["oilp",510],
	["water",2],
	["coffee",1],
	["bandage",1],
	["airkit",1],
	["tierope",50],
	["stitches",1],
	["splint",1],
	["epipen",1],
	["turtlesoup",350],
	["donuts",1],
	["tbacon",1],
	["lockpick",600],
	["pickaxe",5],
	["redgull",1],
	["peach",1],
	["diamond",100],
	["diamondc",250],
	["iron_r",175],
	["copper_r",175],
	["salt_r",125],
	["glass",100],
	["fuelF",50],
	["wheat",25],
	["sunflower",50],
	["corn",90],
	["bean",80],
	["cotton",25],
	["olive",277],
	["opium",100],
	["cannabis",100],
	["pumpkin",110],
	["wheat seed",1],
	["sunflower seed",1],
	["corn seed",1],
	["bean seed",1],
	["cotton seed",1],
	["olive seed",1],
	["opium seed",15],
	["cannabis seed",15],
	["pumpkin seed",5],
	["Raw Meat",550],
	["raw chicken",70],
	["raw sheep meat",50],
	["raw rabbit",70],
	["spikeStrip",12],
	["cement",255],
	["goldbar",9500], 
	//Deo Additions
	["zoobeer",1], 
	["zoobeer2",1],
	["vodka",1],
	["jackdaniels",1],
	["jagerbomb",2],
	["absinthe",2],
	["redwine",2],
	["whitewine",2],
	["whiterussian",2],
	["sexonthebeach",2],
	["tequila",2],
	["jackdanielsandcoke",2],
	["condom",10],
	["nos",10],
	["BarGate",5],
	["RoadBlockConc",2],
	["RoadBlockWood",7],
	["RoadCone",1],
	["RoadConeStrip",2],
	["RoadConeB",1],
	["RoadConeStripB",5],
	["cigarette",1],
	["Rax's Rum",1],
	["Blaulicht",10],
	["tracker",10],
	["silberp",300],
	["titanp",200],
	["gummip",180],
	["krokp",550]
];

__CONST__(sell_array,sell_array);


buy_array =
[
        ["cleankit",100],
        ["medkit",1200],
        ["condom",100],
        ["weddingring",10000],
        ["bandage",25],
        ["airkit",5],
        ["nos",4500],
        ["tierope",1125],
        ["stitches",1],
        ["splint",1],
        ["epipen",1],
        ["marijuana",1500],
        ["methp",1800],
        ["MDMAp",1800],
        ["cokep",1800],
        ["apple",6],
        ["rabbit",7],
        ["bec",50],
        ["mobilephone",1],
        ["panicbutton",1],
        ["salema",129],
        ["ornate",119],
        ["mackerel",125],
        ["tuna",295],
        ["mullet",125],
        ["catshark",220],
        ["marijuana",155],
        ["turtle",700],
        ["water",1],
        ["turtlesoup",250],
        ["donuts",12],
        ["coffee",1],
        ["tbacon",7],
        ["lockpick",1500],
        ["pickaxe",120],
        ["redgull",12],
        ["fuelF",85],
        ["wheat",150],
        ["sunflower",160],
        ["corn",180],
        ["bean",80],
        ["cotton",50],
        ["olive",277],
        ["opium",400],
        ["cannabis",400],
        ["pumpkin",120],
        ["wheat seed",2],
        ["sunflower seed",2],
        ["corn seed",2],
        ["bean seed",2],
        ["cotton seed",2],
        ["olive seed",2],
        ["opium seed",25],
        ["cannabis seed",25],
        ["pumpkin seed",10],
        ["Raw Meat",580],
        ["raw chicken",80],
        ["raw sheep meat",60],
        ["raw rabbit",80],
        ["peach",6],
        ["spikeStrip",250],
        ["blastingcharge",15000],
        ["hackingtool",15000],
        ["boltcutter",2500],
        ["defusekit",250],
        ["storagesmall",7500],
        ["storagebig",15000],
        // Deo's Adds
        ["zoobeer",2],
        ["zoobeer2",2],
        ["vodka",12],
        ["jackdaniels",12],
        ["jagerbomb",22],
        ["absinthe",25],
        ["redwine",22],
        ["whitewine",35],
        ["whiterussian",32],
        ["sexonthebeach",32],
        ["tequila",32],
        ["jackdanielsandcoke",32],
        ["BarGate",50],
        ["RoadBlockConc",3000],
        ["RoadBlockWood",70],
        ["RoadCone",5],
        ["RoadConeStrip",25],
        ["RoadConeB",10],
        ["RoadConeStripB",50],
        ["cigarette",925],
        ["Rax's Rum",5],
        ["Blaulicht",50],
		["tracker",1000],
		["krokp",700]
];
__CONST__(buy_array,buy_array);

life_weapon_shop_array =
[
	["Fish_1_i",70],
	["Fish_2_i",120],
	["Fish_3_i",160],
	["Fish_4_i",100],
	["Fish_5_i",45],
	["ItemGPS",1],
	["ToolKit",1]
];
__CONST__(life_weapon_shop_array,life_weapon_shop_array);

life_garage_prices =
[

			["ADM_General_Lee",0],
			["tcg_hrly",0],
			["tcg_hrly_white",0],	
			["tcg_hrly_red",0],
			["tcg_hrly_metal",0],
			["tcg_hrly_blue",0],
			["tcg_hrly_limited",0],
			["tcg_hrly_demon",0],
			["tcg_hrly_coco",0],
			["tcg_hrly_orig1",0],
			["tcg_hrly_orig2",0],
			["tcg_hrly_skeleton",0],
			["tcg_hrly_gay",0],

			["wirk_h3_limo",0],
			["ivory_wrx_cop_marked",0],
			["ivory_wrx_cop_unmarked",0],
			["ivory_wrx_cop_slicktop",0],
			["cg_evoblack",0],

			//DOC
			["cg_evocor1",0],
			["A3L_SuburbanDOC",0],
			["charger_cor_skinned",0],
			
			//PD
			["cg_cvpifpbpd",0],
			["cg_TaurusPD2",0],
			["cg_evopol1",0],
			["charger_pd",0],
			["charger_pd_skinned",0],
			
			//SO
			["cg_CVPISH",0],
			["cg_TaurusSS1",0],
			["cg_TaurusSS2",0],
			["cg_evoss1",0],
			["charger_sh",0],
			["charger_sh_skinned",0],			

			//ST
			["cg_cvpitrooper",0],
			["cg_taurustrooperf",0],		
			["cg_trooperevo",0],
			["charger_st",0],
			["charger_trp_skinned",0],			
			
			//SERT					
			["AM_Holden_UM",0],	

			["cg_peugeot_207_rc_noir",2000],
			["I_G_Van_01_fuel_F",0],

			["A3L_BMW135Sport1",0],
			["A3L_BMW135Sport2",0],
			["A3L_BMW135Sport3",0],
			["A3L_BMW135Sport4",0],
			["A3L_BMW135Sport5",0],
			["A3L_BMW135White",0],
			["A3L_BMW135Black",0],
			["A3L_BMW135Blue",0],
			["A3L_BMW135Purple",0],
			["A3L_BMW135Red",0],

			["AM_Holden_RBlue",0],			
			["AM_Holden_RRed",0],
			["AM_Holden_RWhite",0],
			["AM_Holden_RBlack",0],

	["AM_Holden_EMS",0],
		["AM_Holden_Police",0],
		["GNT_C185",0],
		["M1030",0],
		["A3L_EvoXrally_green",0],
		["A3L_EvoXrally_white",0],
		["A3L_EvoXrally_red",0],
		["A3L_EvoXrally_blue",0],
		["A3L_EvoXDarkGreen",0],
		["A3L_OffGreen",0],
		["A3L_EvoXOffYellow",0],
		["A3L_EvoXYellow",0],
		["A3L_EvoXPink",0],
		["A3L_EvoXPurple",0],
		["A3L_EvoXWhite",0],
		["A3L_EvoXBlack",0],
		["A3L_EvoXRed",0],
		["EvoXSo1",0],
		["EvoXSo2",0],
		["EvoXSo3",0],
		["EvoXSo4",0],
		["A3L_TaurusPD1",0],
		["A3L_TaurusPD2",0],
		["A3L_SuburbanCSO",0],
		["A3L_Suburban",0],
		["A3L_SuburbanUM",0],
	["B_QuadBike_01_F",0],
	["C_Hatchback_01_F",0],
	["C_Offroad_01_F", 0],
	["B_G_Offroad_01_F",0],
	["C_SUV_01_F",0],
	["C_Van_01_transport_F",0],
	["C_Hatchback_01_sport_F",0],
	["C_Van_01_fuel_F",0],
	["I_Heli_Transport_02_F",0],
	["C_Van_01_box_F",0],
	["I_Truck_02_transport_F",0],
	["I_Truck_02_covered_F",0],
	["B_Truck_01_transport_F",0],
	["B_Truck_01_box_F", 0],
	["O_MRAP_02_F",0],
	["B_Heli_Light_01_F",0],
	["O_Heli_Light_02_unarmed_F",0],
	["C_Rubberboat",0],
	["C_Boat_Civil_01_F",0],
	["B_Boat_Transport_01_F",0],
	["C_Boat_Civil_01_police_F",0],
	["B_Boat_Armed_01_minigun_F",0],
	["B_SDV_01_F",0],
	["A3L_Bus",0],
	["A3L_Karts",0],
	["A3L_Laddertruck",0],
	["A3L_Cooper_concept_blue",0],
	["A3L_Cooper_concept_black",0],
	["A3L_Cooper_concept_red",0],
	["A3L_Cooper_concept_white",0],
	["A3L_AMC",0],
	["A3L_AMXRed",0],
	["A3L_AMXWhite",0],
	["A3L_AMXBlue",0],
	["A3L_AMXGL",0],
	["A3L_VolvoS60RBlack",0],
	["A3L_VolvoS60Rred",0],
	["S_Skyline_Red",0],
	["S_Skyline_Blue",0],
	["S_Skyline_Black",0],
	["S_Skyline_Yellow",0],
	["S_Skyline_Purple",0],
	["S_Skyline_White",0],
	["A3L_Ferrari458black",0],
	["A3L_Ferrari458white",0],
	["A3L_Ferrari458blue",0],
	["A3L_SuburbanWhite",0],
	["A3L_SuburbanBlue",0],
	["A3L_SuburbanRed",0],
	["A3L_SuburbanBlack",0],
	["A3L_SuburbanGrey",0],
	["A3L_SuburbanOrange",0],
	["A3L_TahoeWhite",0],
	["A3L_TahoeRed",0],
	["A3L_TahoeBlue",0],
	["A3L_Camaro",0],
	["A3L_FordKaBlue",0],
	["A3L_FordKaRed",0],
	["A3L_FordKaBlack",0],
	["A3L_FordKaWhite",0],
	["A3L_FordKaGrey",0],
	["A3L_Taurus",0],
	["A3L_TaurusBlack",0],
	["A3L_TaurusBlue",0],
	["A3L_TaurusRed",0],
	["A3L_TaurusWhite",0],
	["A3L_GrandCaravan",0],
	["A3L_GrandCaravanBlk",0],
	["A3L_GrandCaravanBlue",0],
	["A3L_GrandCaravanGreen",0],
	["A3L_GrandCaravanRed",0],
	["A3L_GrandCaravanPurple",0],
	["A3L_Challenger",0],
	["A3L_ChallengerGreen",0],
	["A3L_ChallengerRed",0],
	["A3L_ChallengerWhite",0],
	["A3L_ChallengerBlack",0],
	["A3L_ChallengerBlue",0],

	["A3L_ChargerRed",0],
	["A3L_ChargerBlue",0],
	["A3L_ChargerBlack",0],
	["A3L_ChargerWhite",0],
	["A3L_Charger",0],

	["Jonzie_Viper",0],
	["A3L_Escort",0],
	["CG_Taxi",0],
	["A3L_EscortBlack",0],
	["A3L_EscortBlue",0],
	["A3L_EscortWhite",0],
	["A3L_EscortPink",0],
	["A3L_PuntoRed",0],
	["A3L_PuntoBlack",0],
	["A3L_PuntoWhite",0],
	["A3L_PuntoGrey",0],
	["A3L_RegalBlack",0],
	["A3L_RegalBlue",0],
	["A3L_RegalOrange",0],
	["A3L_RegalRed",0],
	["A3L_RegalWhite",0],
	["A3L_JeepWhiteBlack",0],
	["A3L_JeepGreenBlack",0],
	["A3L_JeepRedTan",0],
	["A3L_JeepRedBlack",0],
	["A3L_JeepGrayBlack",0],
	["A3L_VolksWagenGolfGTired",0],
	["A3L_VolksWagenGolfGTiblack",0],
	["A3L_VolksWagenGolfGTiblue",0],
	["A3L_VolksWagenGolfGTiwhite",0],
	["A3L_F350Black",0],
	["A3L_F350Blue",0],
	["A3L_F350Red",0],
	["A3L_F350White",0],
	["A3L_Dumptruck",0],
	["C_Van_01_box_F",0],
	["C_Van_01_transport_F",0],
	["A3L_GrandCaravanUC",0],
	["A3L_GrandCaravanUCBlack",0],
	["A3L_TaurusFPBLBPD",0],
	["A3L_TaurusFPBLBCSO",0],
	["A3L_TaurusFPBPD",0],
	["A3L_TaurusFPBPDGM",0],
	["A3L_TaurusFPBCSO",0],
	["A3L_TaurusUCBlack",0],
	["A3L_TaurusUCGrey",0],
	["A3L_TaurusUCWhite",0],
	["A3L_TaurusUCBlue",0],
	["A3L_TaurusUCRed",0],
	["A3L_CVPIFPBPD",0],
	["A3L_CVPIFPBCSO",0],
	["A3L_CVPIFPBFG",0],
	["A3L_CVPIFPBLBPD",0],
	["A3L_CVPIFPBLBCSO",0],
	["A3L_CVPIFPBLBFG",0],
	["A3L_TahoeUCPB",0],
	["A3L_TahoeUC",0],
	["A3L_TahoeUCGMPB",0],
	["A3L_TahoeCSOLBPB",0 ],
	["A3L_jailBus",0],
	["A3L_Suburban",0],
	["A3L_SuburbanCSO",0],
	["A3L_SuburbanFG",0],
	["B_MRAP_01_F",7500],
	//MaxRacing
	["IVORY_PRIUS",0],
	["ivory_supra",0],
	["ivory_supra_tuned",0],
	["ivory_isf",0],
	["ivory_m3",0],
	["ivory_m3_gts",0],
	["ivory_wrx",0],
	["ivory_lp560",0],
	["IVORY_R8",0],
	["IVORY_R8SPYDER",0],
	["IVORY_REV",0],	
	["ivory_lfa",0],
	["ivory_c",0],
	["ivory_gt500",0],
	 //showroom_car
	["Jonzie_Quattroporte",0],
	["Jonzie_30CSL",0],
	["Jonzie_Viper",0],
	["Jonzie_Datsun_Z432",0],
	["Jonzie_STI",0],
	["Jonzie_Escalade",0],
	["Jonzie_Datsun_510",0],
	["Jonzie_Ceed",0],
	["Jonzie_Raptor",0],
	["Jonzie_Galant",0],
	["Jonzie_Corolla",0],
	["Jonzie_Mini_Cooper",0],
	["Jonzie_Mini_Cooper_R_spec",0],
	["Jonzie_XB",0],
	["Jonzie_VE",0],
	["Jonzie_Ute",0],
	 //kart_shop
	["A3L_Karts",0],
	["C_Kart_01_Blu_F",0],
	["C_Kart_01_Fuel_F",0],
	["C_Kart_01_Red_F",0],
	["C_Kart_01_Vrana_F",0],
	 //exo_car
	["cg_peugeot_207_rc_noir",0],
	["cg_peugeot_207_rc_violet",0],
	["cg_peugeot_207_rc_rose",0],
	["cg_peugeot_207_rc_orange",0],
	["cg_peugeot_207_rc_grise",0],
	["cg_peugeot_207_rc_vert",0],
	["cg_peugeot_207_rc_bleufonce",0],
	["cg_peugeot_207_rc_bleu",0],
	["cg_peugeot_207_rc_white",0],
	["cg_peugeot_207_rc_jaune",0],
	["cg_volkswagen_touareg_noir",0],
	["cg_volkswagen_touareg_violet",0],
	["cg_volkswagen_touareg_rose",0],
	["cg_volkswagen_touareg_orange",0],
	["cg_volkswagen_touareg_grise",0],
	["cg_volkswagen_touareg_vert",0],
	["cg_volkswagen_touareg_bleufonce",0],
	["cg_volkswagen_touareg_bleu",0],
	["cg_volkswagen_touareg_white",0],
	["cg_volkswagen_touareg_jaune",0],
	["cg_vw_golfvi_noir",0],
	["cg_vw_golfvi_violet",0],
	["cg_vw_golfvi_rose",0],
	["cg_vw_golfvi_orange",0],
	["cg_vw_golfvi_grise",0],
	["cg_vw_golfvi_vert",0],
	["cg_vw_golfvi_bleufonce",0],
	["cg_vw_golfvi_bleu",0],
	["cg_vw_golfvi_white",0],
	["cg_vw_golfvi_jaune",0],
	["cg_jeep_cherokee_noir",0],
	["cg_jeep_cherokee_violet",0],
	["cg_jeep_cherokee_rose",0],
	["cg_jeep_cherokee_orange",0],
	["cg_jeep_cherokee_grise",0],
	["cg_jeep_cherokee_vert",0],
	["cg_jeep_cherokee_bleufonce",0],
	["cg_jeep_cherokee_bleu",0],
	["cg_jeep_cherokee_white",0],
	["cg_jeep_cherokee_jaune",0],
	["cg_audi_rs4_noir",0],
	["cg_audi_rs4_violet",0],
	["cg_audi_rs4_rose",0],
	["cg_audi_rs4_orange",0],
	["cg_audi_rs4_grise",0],
	["cg_audi_rs4_vert",0],
	["cg_audi_rs4_bleufonce",0],
	["cg_audi_rs4_bleu",0],
	["cg_audi_rs4_white",0],
	["cg_audi_rs4_jaune",0],
	["cg_audi_rs5_noir",0],
	["cg_audi_rs5_violet",0],
	["cg_audi_rs5_rose",0],
	["cg_audi_rs5_orange",0],
	["cg_audi_rs5_grise",0],
	["cg_audi_rs5_vert",0],
	["cg_audi_rs5_bleufonce",0],
	["cg_audi_rs5_bleu",0],
	["cg_audi_rs5_white",0],
	["cg_audi_rs5_jaune",0],
	["shounka_rs6_orange",0],
	["shounka_rs6_violet",0],
	["shounka_rs6_grise",0],
	["shounka_rs6_rose",0],
	["shounka_rs6_jaune",0],
	["shounka_rs6_rouge",0],
	["shounka_rs6_bleufonce",0],
	["shounka_rs6",0],
	["shounka_rs6_noir",0],	
	["cg_bmw_1series_m_noir",0],
	["cg_bmw_1series_m_violet",0],
	["cg_bmw_1series_m_rose",0],
	["cg_bmw_1series_m_orange",0],
	["cg_bmw_1series_m_grise",0],
	["cg_bmw_1series_m_vert",0],
	["cg_bmw_1series_m_bleufonce",0],
	["cg_bmw_1series_m_bleu",0],
	["cg_bmw_1series_m_white",0],
	["cg_bmw_1series_m_jaune",0],
	["cg_bmw_m6_noir",0],
	["cg_bmw_m6_violet",0],
	["cg_bmw_m6_rose",0],
	["cg_bmw_m6_orange",0],
	["cg_bmw_m6_bleufonce",0],
	["cg_bmw_m6_bleu",0],
	["cg_bmw_m6_white",0],
	["cg_bmw_m6_jaune",0],						
	["A3L_BMW135Red",0],
	["A3L_BMW135Purple",0],
	["A3L_BMW135Blue",0],
	["A3L_BMW135Black",0],
	["A3L_BMW135White",0],
	["A3L_BMW135Sport5",0],
	["A3L_BMW135Sport4",0],
	["A3L_BMW135Sport3",0],
	["A3L_BMW135Sport2",0],
	["A3L_BMW135Sport1",0], 			
	["cg_renault_megane_rs_2015_noir",0],
	["cg_renault_megane_rs_2015_violet",0],
	["cg_renault_megane_rs_2015_rose",0],
	["cg_renault_megane_rs_2015_orange",0],
	["cg_renault_megane_rs_2015_grise",0],
	["cg_renault_megane_rs_2015_vert",0],
	["cg_renault_megane_rs_2015_bleufonce",0],
	["cg_renault_megane_rs_2015_bleu",0],
	["cg_renault_megane_rs_2015_white",0],
	["cg_renault_megane_rs_2015_jaune",0],
	["Mrshounka_c63_2015_bleufonce",0],
	["Mrshounka_c63_2015_grise",0],
	["Mrshounka_c63_2015_jaune",0],
	["Mrshounka_c63_2015_noir",0],
	["Mrshounka_c63_2015_orange",0],
	["Mrshounka_c63_2015_rose",0],
	["Mrshounka_c63_2015_rouge",0],
	["Mrshounka_c63_2015_violet",0],
	["cg_raptor_truck_noir",0],
	["cg_raptor_truck_violet",0],
	["cg_raptor_truck_rose",0],
	["cg_raptor_truck_orange",0],
	["cg_raptor_truck_grise",0],
	["cg_raptor_truck_vert",0],
	["cg_raptor_truck_bleufonce",0],
	["cg_raptor_truck_bleu",0],
	["cg_raptor_truck_white",0],
	["cg_raptor_truck_jaune",0],
	["cg_porsche_911_82_noir",0],
	["cg_porsche_911_82_violet",0],
	["cg_porsche_911_82_rose",0],
	["cg_porsche_911_82_orange",0],
	["cg_porsche_911_82_grise",0],
	["cg_porsche_911_82_vert",0],
	["cg_porsche_911_82_bleufonce",0],
	["cg_porsche_911_82_bleu",0],
	["cg_porsche_911_82_white",0],
	["cg_porsche_911_82_jaune",0],
	["cg_porsche_cayenne_noir",0],
	["cg_porsche_cayenne_violet",0],
	["cg_porsche_cayenne_rose",0],
	["cg_porsche_cayenne_orange",0],
	["cg_porsche_cayenne_grise",0],
	["cg_porsche_cayenne_vert",0],
	["cg_porsche_cayenne_bleufonce",0],
	["cg_porsche_cayenne_bleu",0],
	["cg_porsche_cayenne_white",0],
	["cg_porsche_cayenne_jaune",0],
	["cg_bowler_offroad_noir",0],
	["cg_bowler_offroad_violet",0],
	["cg_bowler_offroad_rose",0],
	["cg_bowler_offroad_orange",0],
	["cg_bowler_offroad_grise",0],
	["cg_bowler_offroad_vert",0],
	["cg_bowler_offroad_bleufonce",0],
	["cg_bowler_offroad_bleu",0],
	["cg_bowler_offroad_white",0],
	["cg_bowler_offroad_jaune",0],
	["Mrshounka_agera_p_noir",0],
	["Mrshounka_agera_p_bleu",0],
	["Mrshounka_agera_p_jaune",0],			
	["shounka_gt_bleufonce",0],
	["shounka_gt_grise",0],
	["shounka_gt_jaune",0],
	["shounka_gt_noir",0],
	["shounka_gt_orange",0],
	["shounka_gt_rose",0],
	["shounka_gt_rouge",0],
	["shounka_gt_violet",0],
	["Mrshounka_mercedes_190_p_bleufonce",0],
	["Mrshounka_mercedes_190_p_grise",0],
	["Mrshounka_mercedes_190_p_jaune",0],
	["Mrshounka_mercedes_190_p_noir",0],
	["Mrshounka_mercedes_190_p_orange",0],
	["Mrshounka_mercedes_190_p_rose",0],
	["Mrshounka_mercedes_190_p_rouge",0],
	["Mrshounka_mercedes_190_p_violet",0],
	//HOLDENS
	["AM_Holden_White",0],
	["AM_Holden_Black",0],
	["AM_Holden_Green",0],
	["AM_Holden_DarkGreen",0],
	["AM_Holden_OffGreen",0],
	["AM_Holden_blue",0],
	["AM_Holden_OffYellow",0],
	["AM_Holden_Pink",0],
	["AM_Holden_Purple",0],
	["AM_Holden_Yellow",0],
	["cg_nissan_gtr_2012_noir",0],
	["cg_nissan_gtr_2012_violet",0],
	["cg_nissan_gtr_2012_rose",0],
	["cg_nissan_gtr_2012_orange",0],
	["cg_nissan_gtr_2012_grise",0],
	["cg_nissan_gtr_2012_vert",0],
	["cg_nissan_gtr_2012_bleufonce",0],
	["cg_nissan_gtr_2012_bleu",0],
	["cg_nissan_gtr_2012_white",0],
	["cg_nissan_gtr_2012_jaune",0],		
	["shounka_mp4_bleufonce",0],
	["shounka_mp4_grise",0],
	["shounka_mp4_jaune",0],
	["shounka_mp4_noir",0],
	["shounka_mp4_orange",0],
	["shounka_mp4_rose",0],
	["shounka_mp4_rouge",0],
	["shounka_mp4_violet",0],
	["shounka_clk_bleufonce",0],
	["shounka_clk_grise",0],
	["shounka_clk_jaune",0],
	["shounka_clk_noir",0],
	["shounka_clk_orange",0],
	["shounka_clk_rose",0],
	["shounka_clk_rouge",0],
	["shounka_clk_violet",0],
	["cg_jeep_blinde_noir",0],
	["cg_jeep_blinde_violet",0],
	["cg_jeep_blinde_rose",0],
	["cg_jeep_blinde_orange",0],
	["cg_jeep_blinde_grise",0],
	["cg_jeep_blinde_vert",0],
	["cg_jeep_blinde_bleufonce",0],
	["cg_jeep_blinde_bleu",0],
	["cg_jeep_blinde_white",0],
	["cg_jeep_blinde_jaune",0],
	["cg_lancer_evo_x_noir",0],
	["cg_lancer_evo_x_violet",0],
	["cg_lancer_evo_x_rose",0],
	["cg_lancer_evo_x_orange",0],
	["cg_lancer_evo_x_grise",0],
	["cg_lancer_evo_x_vert",0],
	["cg_lancer_evo_x_bleufonce",0],
	["cg_lancer_evo_x_bleu",0],
	["cg_lancer_evo_x_white",0],
	["cg_lancer_evo_x_jaune",0],
	["Mrshounka_pagani_c_bleufonce",0],
	["Mrshounka_pagani_c_grise",0],
	["Mrshounka_pagani_c_jaune",0],
	["Mrshounka_pagani_c_noir",0],
	["Mrshounka_pagani_c_orange",0],
	["Mrshounka_pagani_c_rose",0],
	["Mrshounka_pagani_c_rouge",0],
	["Mrshounka_pagani_c_violet",0],
	["cg_lambo_veneno_noir",0],
	["cg_lambo_veneno_violet",0],
	["cg_lambo_veneno_rose",0],
	["cg_lambo_veneno_orange",0],
	["cg_lambo_veneno_grise",0],
	["cg_lambo_veneno_vert",0],
	["cg_lambo_veneno_bleufonce",0],
	["cg_lambo_veneno_bleu",0],
	["cg_lambo_veneno_white",0],
	["cg_lambo_veneno_jaune",0],
	//Holden racing
	["AM_Holden_RBlue",0],			
	["AM_Holden_RRed",0],
	["AM_Holden_RWhite",0],
	["AM_Holden_RBlack",0],	
	["A3L_Veyron_purple",0],
	["A3L_Veyron_orange",0],
	["A3L_Veyron_red",0],
	["A3L_Veyron_black",0],
	["A3L_Veyron_white",0],
	["A3L_Veyron",0],
	["Mrshounka_lykan_c_bleufonce",0],
	["Mrshounka_lykan_c_grise",0],
	["Mrshounka_lykan_c_jaune",0],
	["Mrshounka_lykan_c_noir",0],
	["Mrshounka_lykan_c_orange",0],
	["Mrshounka_lykan_c_rose",0],
	["Mrshounka_lykan_c_rouge",0],
	["Mrshounka_lykan_c_violet",0],
	["A3L_Ferrari458red",0],
	["A3L_Ferrari458black",0],
	["A3L_Ferrari458white",0],
	["A3L_Ferrari458blue",0],
	["shounka_f430_spider_bleufonce",0],
	["shounka_f430_spider_grise",0],
	["shounka_f430_spider_jaune",0],
	["shounka_f430_spider_noir",0],
	["shounka_f430_spider_orange",0],
	["shounka_f430_spider_rose",0],
	["shounka_f430_spider_rouge",0],
	["shounka_f430_spider_violet",0],
	["shounka_porsche911_bleufonce",0],
	["shounka_porsche911_grise",0],
	["shounka_porsche911_jaune",0],
	["shounka_porsche911_noir",0],
	["shounka_porsche911_orange",0],
	["shounka_porsche911_rose",0],
	["shounka_porsche911_rouge",0],
	["shounka_porsche911_violet",0],
	["CG_Lamborghini_Aventador_Red",0],
	["CG_Lamborghini_Aventador_Black",0],
	["CG_Lamborghini_Aventador_Blue",0],
	["CG_Lamborghini_Aventador_Green",0],
	["CG_Lamborghini_Aventador_Orange",0],
	["CG_Lamborghini_Aventador_Purple",0],
	["CG_Lamborghini_Aventador_White",0],
	["A3L_EvoXrally_green",0],
	["A3L_EvoXrally_white",0],
	["A3L_EvoXrally_red",0],
	["A3L_EvoXrally_blue",0],
	 //chev_car
	["DAR_TahoeCivSilver",0],
	["DAR_TahoeCivBlue",0],
	["DAR_TahoeCivRed",0],
	["DAR_TahoeCivBlack",0],
	["A3L_SuburbanWhite",0],
	["A3L_SuburbanBlue",0],
	["A3L_SuburbanRed",0],
	["A3L_SuburbanBlack",0],
	["A3L_SuburbanGrey",0],
	["A3L_SuburbanOrange",0],
	["A3L_Camaro",0],
	//ford_car
	["cg_raptor_truck_noir",0],
	["cg_raptor_truck_violet",0],
	["cg_raptor_truck_rose",0],
	["cg_raptor_truck_orange",0],
	["cg_raptor_truck_grise",0],
	["cg_raptor_truck_vert",0],
	["cg_raptor_truck_bleufonce",0],
	["cg_raptor_truck_bleu",0],
	["cg_raptor_truck_white",0],
	["cg_raptor_truck_jaune",0],
	["cg_raptor_truck_va_noir",0],
	["cg_raptor_truck_va_violet",0],
	["cg_raptor_truck_va_rose",0],
	["cg_raptor_truck_va_orange",0],
	["cg_raptor_truck_va_grise",0],
	["cg_raptor_truck_va_vert",0],
	["cg_raptor_truck_va_bleufonce",0],
	["cg_raptor_truck_va_bleu",0],
	["cg_raptor_truck_va_white",0],
	["cg_raptor_truck_va_jaune",0],
	["cg_ford_mustang_noir",0],
	["cg_ford_mustang_violet",0],
	["cg_ford_mustang_rose",0],
	["cg_ford_mustang_orange",0],
	["cg_ford_mustang_grise",0],
	["cg_ford_mustang_vert",0],
	["cg_ford_mustang_bleufonce",0],
	["cg_ford_mustang_bleu",0],
	["cg_ford_mustang_white",0],
	["cg_ford_mustang_jaune",0],
	["cg_ford_mustang_rouge",0],
	//dodge_car
	["AM_2015C_Black",0],
	["AM_2015C_blue",0],
	["AM_2015C_white",0],
	["cg_dodge_charger_2015_noir",0],
	["cg_dodge_charger_2015_violet",0],
	["cg_dodge_charger_2015_rose",0],
	["cg_dodge_charger_2015_orange",0],
	["cg_dodge_charger_2015_grise",0],
	["cg_dodge_charger_2015_vert",0],
	["cg_dodge_charger_2015_bleufonce",0],
	["cg_dodge_charger_2015_bleu",0],
	["cg_dodge_charger_2015_white",0],
   ["cg_dodge_charger_2015_jaune",0],
   ["cg_dodge_charger_2015_rouge",0],
   ["A3L_ChallengerWhite",0],
   ["A3L_ChallengerRed",0],
   ["A3L_ChallengerBlack",0],
   ["A3L_ChallengerBlue",0],
   ["A3L_ChallengerGreen",0],
   ["A3L_Challenger",0],
	//civ_car
	["CG_Taxi",0],
	["critgamin_smart_civ",0],
	["critgamin_smart_bleu",0],
	["critgamin_smart_noir",0],
	["critgamin_smart_bleufonce",0],
	["critgamin_smart_rouge",0],
	["critgamin_smart_jaune",0],
	["critgamin_smart_rose",0],
	["critgamin_smart_grise",0],
	["critgamin_smart_violet",0],
	["critgamin_smart_orange",0],
	["critgamin_smart_vert",0],
	["critgamin_contown_civ",0],
	["critgamin_contown_bleu",0],
	["critgamin_contown_noir",0],
	["critgamin_contown_bleufonce",0],
	["critgamin_contown_rouge",0],
	["critgamin_contown_jaune",0],
	["critgamin_contown_rose",0],
	["critgamin_contown_grise",0],
	["critgamin_contown_violet",0],
	["critgamin_contown_jaune",0],
	["critgamin_contown_orange",0],			
	["critgamin_contown_vert",0],
	["critgamin_vangmcc_civ_noir",0],
	["critgamin_vangmcc_civ_bleufonce",0],
	["critgamin_vangmcc_civ_bleu",0],
	["critgamin_vangmcc_civ_vert",0],
	["critgamin_vangmcc_civ_rouge",0],
	["critgamin_vangmcc_civ_jaune",0],
	["critgamin_vangmcc_civ_rose",0],
	["critgamin_vangmcc_civ_grise",0],
	["critgamin_vangmcc_civ_violet",0],
	["critgamin_vangmcc_civ_orange",0],
	["cg_mercedes_sprint_van_noir",0],
	["cg_mercedes_sprint_van_violet",0],
	["cg_mercedes_sprint_van_rose",0],
	["cg_mercedes_sprint_van_orange",0],
	["cg_mercedes_sprint_van_grise",0],
	["cg_mercedes_sprint_van_vert",0],
	["cg_mercedes_sprint_van_bleufonce",0],
	["cg_mercedes_sprint_van_bleu",0],
	["cg_mercedes_sprint_van_white",0],
	["cg_mercedes_sprint_van_jaune",0],
	["cg_mercedes_sprint_van_rouge",0],
	["cg_citroen_c4_noir",0],
	["cg_citroen_c4_violet",0],
	["cg_citroen_c4_rose",0],
	["cg_citroen_c4_orange",0],
	["cg_citroen_c4_grise",0],
	["cg_citroen_c4_vert",0],
	["cg_citroen_c4_bleufonce",0],
	["cg_citroen_c4_bleu",0],
	["cg_citroen_c4_white",0],
	["cg_citroen_c4_jaune",0],
	["cg_citroen_c4_rouge",0],
	["cg_renault_twingo_noir",0],
	["cg_renault_twingo_violet",0],
	["cg_renault_twingo_rose",0],
	["cg_renault_twingo_orange",0],
	["cg_renault_twingo_grise",0],
	["cg_renault_twingo_vert",0],
	["cg_renault_twingo_bleufonce",0],
	["cg_renault_twingo_bleu",0],
	["cg_renault_twingo_white",0],
	["cg_renault_twingo_jaune",0],
	["cg_renault_twingo_rouge",0],
	["cg_citroen_ds3_noir",0],
	["cg_citroen_ds3_violet",0],
	["cg_citroen_ds3_rose",0],
	["cg_citroen_ds3_orange",0],
	["cg_citroen_ds3_grise",0],
	["cg_citroen_ds3_vert",0],
	["cg_citroen_ds3_bleufonce",0],
	["cg_citroen_ds3_bleu",0],
	["cg_citroen_ds3_white",0],
	["cg_citroen_ds3_jaune",0],
	["cg_citroen_ds3_rouge",0],
	["cg_citroen_ds4_noir",0],
	["cg_citroen_ds4_violet",0],
	["cg_citroen_ds4_rose",0],
	["cg_citroen_ds4_orange",0],
	["cg_citroen_ds4_grise",0],
	["cg_citroen_ds4_vert",0],
	["cg_citroen_ds4_bleufonce",0],
	["cg_citroen_ds4_bleu",0],
	["cg_citroen_ds4_white",0],
	["cg_citroen_ds4_jaune",0],
	["cg_citroen_ds4_rouge",0],
	["cg_peugeot_308_gti_civ_noir",0],
	["cg_peugeot_308_gti_civ_violet",0],
	["cg_peugeot_308_gti_civ_rose",0],
	["cg_peugeot_308_gti_civ_orange",0],
	["cg_peugeot_308_gti_civ_grise",0],
	["cg_peugeot_308_gti_civ_vert",0],
	["cg_peugeot_308_gti_civ_bleufonce",0],
	["cg_peugeot_308_gti_civ_bleu",0],
	["cg_peugeot_308_gti_civ_white",0],
	["cg_peugeot_308_gti_civ_jaune",0],
	["cg_peugeot_308_gti_civ_rouge",0],
	["cg_peugeot_308_rcz_noir",0],
	["cg_peugeot_308_rcz_violet",0],
	["cg_peugeot_308_rcz_rose",0],
	["cg_peugeot_308_rcz_orange",0],
	["cg_peugeot_308_rcz_grise",0],
	["cg_peugeot_308_rcz_vert",0],
	["cg_peugeot_308_rcz_bleufonce",0],
	["cg_peugeot_308_rcz_bleu",0],
	["cg_peugeot_308_rcz_white",0],
	["cg_peugeot_308_rcz_jaune",0],
	["cg_peugeot_308_rcz_rouge",0],
	["Mrshounka_Alfa_Romeo_bleufonce",0],
	["Mrshounka_Alfa_Romeo_grise",0],
	["Mrshounka_Alfa_Romeo_jaune",0],
	["Mrshounka_Alfa_Romeo_noir",0],
	["Mrshounka_Alfa_Romeo_orange",0],
	["Mrshounka_Alfa_Romeo_rose",0],
	["Mrshounka_Alfa_Romeo_rouge",0],
	["Mrshounka_Alfa_Romeo_violet",0],
	["S_Rangerover_Black",0],
	["S_Rangerover_Red",0],
	["S_Rangerover_Blue",0],
	["S_Rangerover_Green",0],
	["S_Rangerover_Purple",0],
	["S_Rangerover_Grey",0],
	["S_Rangerover_Orange",0],
	["S_Rangerover_White",0],
	["POP_Qashqai_amarillo",0],
	["pop_toyota_gt86_Blanco",0],
	["pop_toyota_gt86_silver",0],
	["pop_toyota_gt86_gris",0],
	["pop_toyota_gt86_negro",0],
	["pop_toyota_gt86_azul",0],
	["pop_toyota_gt86_rojo",0],
	["cg_peugeot_508_civ_noir",0],
	["cg_peugeot_508_civ_violet",0],
	["cg_peugeot_508_civ_rose",0],
	["cg_peugeot_508_civ_orange",0],
	["cg_peugeot_508_civ_grise",0],
	["cg_peugeot_508_civ_vert",0],
	["cg_peugeot_508_civ_bleufonce",0],
	["cg_peugeot_508_civ_bleu",0],
	["cg_peugeot_508_civ_white",0],
	["cg_peugeot_508_civ_jaune",0],
	["cg_peugeot_508_civ_rouge",0],
	["A3L_JeepGrayBlack",0],
	["A3L_JeepGrayTan",0],
	["A3L_JeepTanTan",0],
	["A3L_JeepTanBlack",0],
	["A3L_JeepRedBlack",0],
	["A3L_JeepRedTan",0],
	["A3L_JeepGreenBlack",0],
	["A3L_JeepGreenTan",0],
	["A3L_JeepWhiteBlack",0],
	["A3L_Jeep",0],
	["shounka_transam_orange",0],
	["shounka_transam_violet",0],
	["shounka_transam_grise",0],
	["shounka_transam_rose",0],
	["shounka_transam_jaune",0],
	["shounka_transam_rouge",0],
	["shounka_transam_bleufonce",0],
	["shounka_transam_noir",0],
	["shounka_transam",0],
	//civ_motorbike
	["tcg_hrly",0],
	["tcg_hrly_white",0],	
	["tcg_hrly_red",0],
	["tcg_hrly_metal",0],
	["tcg_hrly_blue",0],
	["tcg_hrly_limited",0],
	["tcg_hrly_demon",0],
	["tcg_hrly_coco",0],
	["tcg_hrly_orig1",0],
	["tcg_hrly_orig2",0],
	["tcg_hrly_skeleton",0],
	["tcg_hrly_gay",0],
	["cg_ducati_civ_noir",0],
	["cg_ducati_civ_violet",0],
	["cg_ducati_civ_rose",0],
	["cg_ducati_civ_orange",0],
	["cg_ducati_civ_grise",0],
	["cg_ducati_civ_vert",0],
	["cg_ducati_civ_bleufonce",0],
	["cg_ducati_civ_bleu",0],
	["cg_ducati_civ_white",0],
	["cg_ducati_civ_jaune",0],
	["cg_ducati_civ_rouge",0],
	 //civ_truck
	["Jonzie_Transit",0],
	["C_Van_01_fuel_F",0],
	["C_Van_01_box_F",0],
	["C_Van_01_transport_F",0],
	["shounka_nemo_bleufonce",0],
	["shounka_nemo_grise",0],
	["shounka_nemo_jaune",0],
	["shounka_nemo_noir",0],
	["shounka_nemo_orange",0],
	["shounka_nemo_rose",0],
	["shounka_nemo_rouge",0],
	["shounka_nemo_violet",0],
	["cg_hummer_h1_noir",0],
	["cg_hummer_h1_violet",0],
	["cg_hummer_h1_rose",0],
	["cg_hummer_h1_orange",0],
	["cg_hummer_h1_grise",0],
	["cg_hummer_h1_vert",0],
	["cg_hummer_h1_bleufonce",0],
	["cg_hummer_h1_bleu",0],
	["cg_hummer_h1_white",0],
	["cg_hummer_h1_jaune",0],
	["shounka_h2_bleufonce",0],
	["shounka_h2_grise",0],
	["shounka_h2_jaune",0],
	["shounka_h2_noir",0],
	["shounka_h2_orange",0],
	["shounka_h2_rose",0],
	["shounka_h2_rouge",0],
	["shounka_h2_violet",0],
	["A3L_Bus",0],
	["pop_bus_p",0],
	["cg_daf_xf_euro6_noir",0],
	["cg_daf_xf_euro6_violet",0],
	["cg_daf_xf_euro6_rose",0],
	["cg_daf_xf_euro6_orange",0],
	["cg_daf_xf_euro6_grise",0],
	["cg_daf_xf_euro6_vert",0],
	["cg_daf_xf_euro6_bleufonce",0],
	["cg_daf_xf_euro6_white",0],
	["cg_daf_xf_euro6_jaune",0],
	["cg_daf_xf_euro6_rouge",0],
	["Jonzie_Flat_Bed",0],
	["Jonzie_Log_Truck",0],
	["Jonzie_Box_Truck",0],
	["Jonzie_Tanker_Truck",0],
	["cg_renault_magnum_truck_f_noir",0],
	["cg_renault_magnum_truck_f_violet",0],
	["cg_renault_magnum_truck_f_rose",0],
	["cg_renault_magnum_truck_f_orange",0],
	["cg_renault_magnum_truck_f_grise",0],
	["cg_renault_magnum_truck_f_vert",0],
	["cg_renault_magnum_truck_f_white",0],
	["cg_renault_magnum_truck_f_jaune",0],
	["shounka_avalanche_bleufonce",0],
	["shounka_avalanche_grise",0],
	["shounka_avalanche_jaune",0],
	["shounka_avalanche_noir",0],
	["shounka_avalanche_orange",0],
	["shounka_avalanche_rose",0],
	["shounka_avalanche_rouge",0],
	["shounka_avalanche_violet",0],
	["shounka_ivceco_bleufonce",0],
	["shounka_ivceco_grise",0],
	["shounka_ivceco_jaune",0],
	["shounka_ivceco_noir",0],
	["shounka_ivceco_orange",0],
	["shounka_ivceco_rose",0],
	["shounka_ivceco_rouge",0],
	["shounka_ivceco_violet",0],
	["Nhz_audia8limo",0],
	["cg_audi_a8_limo_noir",0],
	["cg_audi_a8_limo_violet",0],
	["cg_audi_a8_limo_rose",0],
	["cg_audi_a8_limo_orange",0],
	["cg_audi_a8_limo_grise",0],
	["cg_audi_a8_limo_vert",0],
	["cg_audi_a8_limo_bleufonce",0],
	["cg_audi_a8_limo_bleu",0],
	["cg_audi_a8_limo_white",0],
	["cg_audi_a8_limo_jaune",0],
	["wirk_h3_limo",0],
	 //reb_car
	["B_Quadbike_01_F",0],
	["I_G_Van_01_fuel_F",0],
	["B_Heli_Light_01_F",0],
	["B_G_Offroad_01_F",0],
	["O_Heli_Light_02_unarmed_F",0],
	 //cop_car
	["ivory_wrx_marked",0],
	["ivory_wrx_unmarked",0],
	["ivory_wrx_slicktop",0],
	["ivory_isf_unmarked",0],
	["ivory_isf_slicktop",0],
	["ivory_m3_unmarked",0],
	["ivory_m3_slicktop",0],
	["A3L_CVPIFPBDOC",0],
	["A3L_TaurusCO2",0],
	["cg_cvpifpblbpd",0],	
	["cg_TaurusPD1",0],	
	["DAR_ExplorerPolice",0],
	["charger_pd_skinned",0],
	["cg_ss2",0],
	["DAR_ExplorerSheriff",0],
	["charger_sh_skinned",0],			
	["cg_suburban_sert_pol",0],					
	["cg_evoSERT1",0],
	["charger_sert",0],
	["cg_h2_sert",0],	
	["AM_Holden_SO",0],		
	["A3L_CVPIUC",0],
	["A3L_CVPIUCBlack",0],
	["A3L_CVPIUCBlue",0],
	["cg_mercedes_sprinter_pol_base_reg",0],
	["cg_ducati_pol_reg",0],			
	["DAR_ExplorerPoliceStealth",0],			
	["A3L_jailBus",0],
	 //civ_air
	["B_Heli_Light_01_F",0],
	["ivory_b206",0],
	["ivory_b206_news",0],
	["CUP_C_DC3_CIV",0],
	["CUP_C_C47_CIV",0],			
	["GNT_C185",0],
	["IVORY_CRJ200_1",0],
	["IVORY_ERJ135_1",0],
	 //cop_air	
	["B_Heli_Light_01_F",0],
	["C_Heli_Light_01_civil_F",0],
	["EC635_SAR",0],
	["EC635_PRPG_SERT",0],
	["melb_h6m",0],
	["B_Heli_Light_01_F",0],
	["EC635_SAR",0],
	["EC635_PRPG_SERT",0],
	["C_Heli_Light_01_civil_F",0],
	["EC635_prpg_lvsf",0],
	["Urbanized_LaFerrari_red",0],
	["Urbanized_LaFerrari_black",0],
	["Urbanized_LaFerrari_white",0],
	["Urbanized_LaFerrari_blue",0],
	["Urbanized_LaFerrari_purple",0],
	["Urbanized_LaFerrari_pink",0],
	["Urbanized_LaFerrari_orange",0],
	["Urbanized_LaFerrari_darkred",0],
	["Urbanized_LaFerrari_hotpink",0],
	["Urbanized_LaFerrari_yellow",0],
	["Urbanized_LaFerrari_lime",0],
	["Urbanized_LaFerrari_Blue_Special",0],
	["Urbanized_LaFerrari_Lime_Special",0],

	["EC635_prpg_presidental",0]
	
	
];
__CONST__(life_garage_prices,life_garage_prices);

life_impound_prices =
[
			["ADM_General_Lee",10],
			["ivory_wrx_cop_marked",10],
			["ivory_wrx_cop_unmarked",10],
			["ivory_wrx_cop_slicktop",10],
			["cg_evoblack",10],

			//DOC
			["cg_evocor1",10],
			["A3L_SuburbanDOC",10],
			["charger_cor_skinned",10],
			
			//PD
			["cg_cvpifpbpd",10],
			["cg_TaurusPD2",10],
			["cg_evopol1",10],
			["charger_pd",10],
			["charger_pd_skinned",10],
			
			//SO
			["cg_CVPISH",10],
			["cg_TaurusSS1",10],
			["cg_TaurusSS2",10],
			["cg_evoss1",10],
			["charger_sh",10],
			["charger_sh_skinned",10],			

			//ST
			["cg_cvpitrooper",10],
			["cg_taurustrooperf",10],		
			["cg_trooperevo",10],
			["charger_st",10],
			["charger_trp_skinned",10],			
			
			//SERT					
			["AM_Holden_UM",10],
			
			["tcg_hrly",10],
			["tcg_hrly_white",10],	
			["tcg_hrly_red",10],
			["tcg_hrly_metal",10],
			["tcg_hrly_blue",10],
			["tcg_hrly_limited",10],
			["tcg_hrly_demon",10],
			["tcg_hrly_coco",10],
			["tcg_hrly_orig1",10],
			["tcg_hrly_orig2",10],
			["tcg_hrly_skeleton",10],
			["tcg_hrly_gay",10],
			["RR_Firetruck",10],
			["cg_ambulanceexpansion",10],
			["A3L_TowTruck_ADAC",10],
			["cg_evoems1",10],
			["cg_evoems2",10],
			["cg_evoems3",10],

			["wirk_h3_limo",10],

			["cg_peugeot_207_rc_noir",10],
			["I_G_Van_01_fuel_F",10],

			["A3L_BMW135Sport1",10],
			["A3L_BMW135Sport2",10],
			["A3L_BMW135Sport3",10],
			["A3L_BMW135Sport4",10],
			["A3L_BMW135Sport5",10],
			["A3L_BMW135White",10],
			["A3L_BMW135Black",10],
			["A3L_BMW135Blue",10],
			["A3L_BMW135Purple",10],
			["A3L_BMW135Red",10],

			["AM_Holden_RBlue",10],			
			["AM_Holden_RRed",10],
			["AM_Holden_RWhite",10],
			["AM_Holden_RBlack",10],

	["AM_Holden_EMS",10],
		["AM_Holden_Police",10],
		["GNT_C185",10],
		["M1030",10],
		["A3L_EvoXrally_green",10],
		["A3L_EvoXrally_white",10],
		["A3L_EvoXrally_red",10],
		["A3L_EvoXrally_blue",10],
		["A3L_EvoXDarkGreen",10],
		["A3L_OffGreen",10],
		["A3L_EvoXOffYellow",10],
		["A3L_EvoXYellow",10],
		["A3L_EvoXPink",10],
		["A3L_EvoXPurple",10],
		["A3L_EvoXWhite",10],
		["A3L_EvoXBlack",10],
		["A3L_EvoXRed",10],
		["EvoXSo1",10],
		["EvoXSo2",10],
		["EvoXSo3",10],
		["EvoXSo4",10],
		["A3L_TaurusPD1",10],
		["A3L_TaurusPD2",10],
		["A3L_SuburbanCSO",10],
		["A3L_Suburban",10],
		["A3L_SuburbanUM",10],
	["B_QuadBike_01_F",10],
	["C_Hatchback_01_F",10],
	["C_Offroad_01_F", 0],
	["B_G_Offroad_01_F",10],
	["C_SUV_01_F",10],
	["C_Van_01_transport_F",10],
	["C_Hatchback_01_sport_F",10],
	["C_Van_01_fuel_F",10],
	["I_Heli_Transport_02_F",10],
	["C_Van_01_box_F",10],
	["I_Truck_02_transport_F",10],
	["I_Truck_02_covered_F",10],
	["B_Truck_01_transport_F",10],
	["B_Truck_01_box_F", 0],
	["O_MRAP_02_F",10],
	["B_Heli_Light_01_F",10],
	["O_Heli_Light_02_unarmed_F",10],
	["C_Rubberboat",10],
	["C_Boat_Civil_01_F",10],
	["B_Boat_Transport_01_F",10],
	["C_Boat_Civil_01_police_F",10],
	["B_Boat_Armed_01_minigun_F",10],
	["B_SDV_01_F",10],
	["A3L_Bus",10],
	["A3L_Karts",10],
	["A3L_Laddertruck",10],
	["A3L_Cooper_concept_blue",10],
	["A3L_Cooper_concept_black",10],
	["A3L_Cooper_concept_red",10],
	["A3L_Cooper_concept_white",10],
	["A3L_AMC",10],
	["A3L_AMXRed",10],
	["A3L_AMXWhite",10],
	["A3L_AMXBlue",10],
	["A3L_AMXGL",10],
	["A3L_VolvoS60RBlack",10],
	["A3L_VolvoS60Rred",10],
	["S_Skyline_Red",10],
	["S_Skyline_Blue",10],
	["S_Skyline_Black",10],
	["S_Skyline_Yellow",10],
	["S_Skyline_Purple",10],
	["S_Skyline_White",10],
	["A3L_Ferrari458black",10],
	["A3L_Ferrari458white",10],
	["A3L_Ferrari458blue",10],
	["A3L_SuburbanWhite",10],
	["A3L_SuburbanBlue",10],
	["A3L_SuburbanRed",10],
	["A3L_SuburbanBlack",10],
	["A3L_SuburbanGrey",10],
	["A3L_SuburbanOrange",10],
	["A3L_TahoeWhite",10],
	["A3L_TahoeRed",10],
	["A3L_TahoeBlue",10],
	["A3L_Camaro",10],
	["A3L_FordKaBlue",10],
	["A3L_FordKaRed",10],
	["A3L_FordKaBlack",10],
	["A3L_FordKaWhite",10],
	["A3L_FordKaGrey",10],
	["A3L_Taurus",10],
	["A3L_TaurusBlack",10],
	["A3L_TaurusBlue",10],
	["A3L_TaurusRed",10],
	["A3L_TaurusWhite",10],
	["A3L_GrandCaravan",10],
	["A3L_GrandCaravanBlk",10],
	["A3L_GrandCaravanBlue",10],
	["A3L_GrandCaravanGreen",10],
	["A3L_GrandCaravanRed",10],
	["A3L_GrandCaravanPurple",10],
	["A3L_Challenger",10],
	["A3L_ChallengerGreen",10],
	["A3L_ChallengerRed",10],
	["A3L_ChallengerWhite",10],
	["A3L_ChallengerBlack",10],
	["A3L_ChallengerBlue",10],

	["A3L_ChargerRed",10],
	["A3L_ChargerBlue",10],
	["A3L_ChargerBlack",10],
	["A3L_ChargerWhite",10],
	["A3L_Charger",10],

	["Jonzie_Viper",10],
	["A3L_Escort",10],
	["CG_Taxi",10],
	["A3L_EscortBlack",10],
	["A3L_EscortBlue",10],
	["A3L_EscortWhite",10],
	["A3L_EscortPink",10],
	["A3L_PuntoRed",10],
	["A3L_PuntoBlack",10],
	["A3L_PuntoWhite",10],
	["A3L_PuntoGrey",10],
	["A3L_RegalBlack",10],
	["A3L_RegalBlue",10],
	["A3L_RegalOrange",10],
	["A3L_RegalRed",10],
	["A3L_RegalWhite",10],
	["A3L_JeepWhiteBlack",10],
	["A3L_JeepGreenBlack",10],
	["A3L_JeepRedTan",10],
	["A3L_JeepRedBlack",10],
	["A3L_JeepGrayBlack",10],
	["A3L_VolksWagenGolfGTired",10],
	["A3L_VolksWagenGolfGTiblack",10],
	["A3L_VolksWagenGolfGTiblue",10],
	["A3L_VolksWagenGolfGTiwhite",10],
	["A3L_F350Black",10],
	["A3L_F350Blue",10],
	["A3L_F350Red",10],
	["A3L_F350White",10],
	["A3L_Dumptruck",10],
	["C_Van_01_box_F",10],
	["C_Van_01_transport_F",10],
	["A3L_GrandCaravanUC",10],
	["A3L_GrandCaravanUCBlack",10],
	["A3L_TaurusFPBLBPD",10],
	["A3L_TaurusFPBLBCSO",10],
	["A3L_TaurusFPBPD",10],
	["A3L_TaurusFPBPDGM",10],
	["A3L_TaurusFPBCSO",10],
	["A3L_TaurusUCBlack",10],
	["A3L_TaurusUCGrey",10],
	["A3L_TaurusUCWhite",10],
	["A3L_TaurusUCBlue",10],
	["A3L_TaurusUCRed",10],
	["A3L_CVPIFPBPD",10],
	["A3L_CVPIFPBCSO",10],
	["A3L_CVPIFPBFG",10],
	["A3L_CVPIFPBLBPD",10],
	["A3L_CVPIFPBLBCSO",10],
	["A3L_CVPIFPBLBFG",10],
	["A3L_TahoeUCPB",10],
	["A3L_TahoeUC",10],
	["A3L_TahoeUCGMPB",10],
	["A3L_TahoeCSOLBPB",10 ],
	["A3L_jailBus",10],
	["A3L_Suburban",10],
	["A3L_SuburbanCSO",10],
	["A3L_SuburbanFG",10],
	["B_MRAP_01_F",7500],
	//MaxRacing
	["IVORY_PRIUS",10],
	["ivory_supra",10],
	["ivory_supra_tuned",10],
	["ivory_isf",10],
	["ivory_m3",10],
	["ivory_m3_gts",10],
	["ivory_wrx",10],
	["ivory_lp560",10],
	["IVORY_R8",10],
	["IVORY_R8SPYDER",10],
	["IVORY_REV",10],	
	["ivory_lfa",10],
	["ivory_c",10],
	["ivory_gt500",10],
	 //showroom_car
	["Jonzie_Quattroporte",10],
	["Jonzie_30CSL",10],
	["Jonzie_Viper",10],
	["Jonzie_Datsun_Z432",10],
	["Jonzie_STI",10],
	["Jonzie_Escalade",10],
	["Jonzie_Datsun_510",10],
	["Jonzie_Ceed",10],
	["Jonzie_Raptor",10],
	["Jonzie_Galant",10],
	["Jonzie_Corolla",10],
	["Jonzie_Mini_Cooper",10],
	["Jonzie_Mini_Cooper_R_spec",10],
	["Jonzie_XB",10],
	["Jonzie_VE",10],
	["Jonzie_Ute",10],
	 //kart_shop
	["A3L_Karts",10],
	["C_Kart_01_Blu_F",10],
	["C_Kart_01_Fuel_F",10],
	["C_Kart_01_Red_F",10],
	["C_Kart_01_Vrana_F",10],
	 //exo_car
	["cg_peugeot_207_rc_noir",10],
	["cg_peugeot_207_rc_violet",10],
	["cg_peugeot_207_rc_rose",10],
	["cg_peugeot_207_rc_orange",10],
	["cg_peugeot_207_rc_grise",10],
	["cg_peugeot_207_rc_vert",10],
	["cg_peugeot_207_rc_bleufonce",10],
	["cg_peugeot_207_rc_bleu",10],
	["cg_peugeot_207_rc_white",10],
	["cg_peugeot_207_rc_jaune",10],
	["cg_volkswagen_touareg_noir",10],
	["cg_volkswagen_touareg_violet",10],
	["cg_volkswagen_touareg_rose",10],
	["cg_volkswagen_touareg_orange",10],
	["cg_volkswagen_touareg_grise",10],
	["cg_volkswagen_touareg_vert",10],
	["cg_volkswagen_touareg_bleufonce",10],
	["cg_volkswagen_touareg_bleu",10],
	["cg_volkswagen_touareg_white",10],
	["cg_volkswagen_touareg_jaune",10],
	["cg_vw_golfvi_noir",10],
	["cg_vw_golfvi_violet",10],
	["cg_vw_golfvi_rose",10],
	["cg_vw_golfvi_orange",10],
	["cg_vw_golfvi_grise",10],
	["cg_vw_golfvi_vert",10],
	["cg_vw_golfvi_bleufonce",10],
	["cg_vw_golfvi_bleu",10],
	["cg_vw_golfvi_white",10],
	["cg_vw_golfvi_jaune",10],
	["cg_jeep_cherokee_noir",10],
	["cg_jeep_cherokee_violet",10],
	["cg_jeep_cherokee_rose",10],
	["cg_jeep_cherokee_orange",10],
	["cg_jeep_cherokee_grise",10],
	["cg_jeep_cherokee_vert",10],
	["cg_jeep_cherokee_bleufonce",10],
	["cg_jeep_cherokee_bleu",10],
	["cg_jeep_cherokee_white",10],
	["cg_jeep_cherokee_jaune",10],
	["cg_audi_rs4_noir",10],
	["cg_audi_rs4_violet",10],
	["cg_audi_rs4_rose",10],
	["cg_audi_rs4_orange",10],
	["cg_audi_rs4_grise",10],
	["cg_audi_rs4_vert",10],
	["cg_audi_rs4_bleufonce",10],
	["cg_audi_rs4_bleu",10],
	["cg_audi_rs4_white",10],
	["cg_audi_rs4_jaune",10],
	["cg_audi_rs5_noir",10],
	["cg_audi_rs5_violet",10],
	["cg_audi_rs5_rose",10],
	["cg_audi_rs5_orange",10],
	["cg_audi_rs5_grise",10],
	["cg_audi_rs5_vert",10],
	["cg_audi_rs5_bleufonce",10],
	["cg_audi_rs5_bleu",10],
	["cg_audi_rs5_white",10],
	["cg_audi_rs5_jaune",10],
	["shounka_rs6_orange",10],
	["shounka_rs6_violet",10],
	["shounka_rs6_grise",10],
	["shounka_rs6_rose",10],
	["shounka_rs6_jaune",10],
	["shounka_rs6_rouge",10],
	["shounka_rs6_bleufonce",10],
	["shounka_rs6",10],
	["shounka_rs6_noir",10],	
	["cg_bmw_1series_m_noir",10],
	["cg_bmw_1series_m_violet",10],
	["cg_bmw_1series_m_rose",10],
	["cg_bmw_1series_m_orange",10],
	["cg_bmw_1series_m_grise",10],
	["cg_bmw_1series_m_vert",10],
	["cg_bmw_1series_m_bleufonce",10],
	["cg_bmw_1series_m_bleu",10],
	["cg_bmw_1series_m_white",10],
	["cg_bmw_1series_m_jaune",10],
	["cg_bmw_m6_noir",10],
	["cg_bmw_m6_violet",10],
	["cg_bmw_m6_rose",10],
	["cg_bmw_m6_orange",10],
	["cg_bmw_m6_bleufonce",10],
	["cg_bmw_m6_bleu",10],
	["cg_bmw_m6_white",10],
	["cg_bmw_m6_jaune",10],						
	["A3L_BMW135Red",10],
	["A3L_BMW135Purple",10],
	["A3L_BMW135Blue",10],
	["A3L_BMW135Black",10],
	["A3L_BMW135White",10],
	["A3L_BMW135Sport5",10],
	["A3L_BMW135Sport4",10],
	["A3L_BMW135Sport3",10],
	["A3L_BMW135Sport2",10],
	["A3L_BMW135Sport1",10], 			
	["cg_renault_megane_rs_2015_noir",10],
	["cg_renault_megane_rs_2015_violet",10],
	["cg_renault_megane_rs_2015_rose",10],
	["cg_renault_megane_rs_2015_orange",10],
	["cg_renault_megane_rs_2015_grise",10],
	["cg_renault_megane_rs_2015_vert",10],
	["cg_renault_megane_rs_2015_bleufonce",10],
	["cg_renault_megane_rs_2015_bleu",10],
	["cg_renault_megane_rs_2015_white",10],
	["cg_renault_megane_rs_2015_jaune",10],
	["Mrshounka_c63_2015_bleufonce",10],
	["Mrshounka_c63_2015_grise",10],
	["Mrshounka_c63_2015_jaune",10],
	["Mrshounka_c63_2015_noir",10],
	["Mrshounka_c63_2015_orange",10],
	["Mrshounka_c63_2015_rose",10],
	["Mrshounka_c63_2015_rouge",10],
	["Mrshounka_c63_2015_violet",10],
	["cg_raptor_truck_noir",10],
	["cg_raptor_truck_violet",10],
	["cg_raptor_truck_rose",10],
	["cg_raptor_truck_orange",10],
	["cg_raptor_truck_grise",10],
	["cg_raptor_truck_vert",10],
	["cg_raptor_truck_bleufonce",10],
	["cg_raptor_truck_bleu",10],
	["cg_raptor_truck_white",10],
	["cg_raptor_truck_jaune",10],
	["cg_porsche_911_82_noir",10],
	["cg_porsche_911_82_violet",10],
	["cg_porsche_911_82_rose",10],
	["cg_porsche_911_82_orange",10],
	["cg_porsche_911_82_grise",10],
	["cg_porsche_911_82_vert",10],
	["cg_porsche_911_82_bleufonce",10],
	["cg_porsche_911_82_bleu",10],
	["cg_porsche_911_82_white",10],
	["cg_porsche_911_82_jaune",10],
	["cg_porsche_cayenne_noir",10],
	["cg_porsche_cayenne_violet",10],
	["cg_porsche_cayenne_rose",10],
	["cg_porsche_cayenne_orange",10],
	["cg_porsche_cayenne_grise",10],
	["cg_porsche_cayenne_vert",10],
	["cg_porsche_cayenne_bleufonce",10],
	["cg_porsche_cayenne_bleu",10],
	["cg_porsche_cayenne_white",10],
	["cg_porsche_cayenne_jaune",10],
	["cg_bowler_offroad_noir",10],
	["cg_bowler_offroad_violet",10],
	["cg_bowler_offroad_rose",10],
	["cg_bowler_offroad_orange",10],
	["cg_bowler_offroad_grise",10],
	["cg_bowler_offroad_vert",10],
	["cg_bowler_offroad_bleufonce",10],
	["cg_bowler_offroad_bleu",10],
	["cg_bowler_offroad_white",10],
	["cg_bowler_offroad_jaune",10],
	["Mrshounka_agera_p_noir",10],
	["Mrshounka_agera_p_bleu",10],
	["Mrshounka_agera_p_jaune",10],			
	["shounka_gt_bleufonce",10],
	["shounka_gt_grise",10],
	["shounka_gt_jaune",10],
	["shounka_gt_noir",10],
	["shounka_gt_orange",10],
	["shounka_gt_rose",10],
	["shounka_gt_rouge",10],
	["shounka_gt_violet",10],
	["Mrshounka_mercedes_190_p_bleufonce",10],
	["Mrshounka_mercedes_190_p_grise",10],
	["Mrshounka_mercedes_190_p_jaune",10],
	["Mrshounka_mercedes_190_p_noir",10],
	["Mrshounka_mercedes_190_p_orange",10],
	["Mrshounka_mercedes_190_p_rose",10],
	["Mrshounka_mercedes_190_p_rouge",10],
	["Mrshounka_mercedes_190_p_violet",10],
	//HOLDENS
	["AM_Holden_White",10],
	["AM_Holden_Black",10],
	["AM_Holden_Green",10],
	["AM_Holden_DarkGreen",10],
	["AM_Holden_OffGreen",10],
	["AM_Holden_blue",10],
	["AM_Holden_OffYellow",10],
	["AM_Holden_Pink",10],
	["AM_Holden_Purple",10],
	["AM_Holden_Yellow",10],
	["cg_nissan_gtr_2012_noir",10],
	["cg_nissan_gtr_2012_violet",10],
	["cg_nissan_gtr_2012_rose",10],
	["cg_nissan_gtr_2012_orange",10],
	["cg_nissan_gtr_2012_grise",10],
	["cg_nissan_gtr_2012_vert",10],
	["cg_nissan_gtr_2012_bleufonce",10],
	["cg_nissan_gtr_2012_bleu",10],
	["cg_nissan_gtr_2012_white",10],
	["cg_nissan_gtr_2012_jaune",10],		
	["shounka_mp4_bleufonce",10],
	["shounka_mp4_grise",10],
	["shounka_mp4_jaune",10],
	["shounka_mp4_noir",10],
	["shounka_mp4_orange",10],
	["shounka_mp4_rose",10],
	["shounka_mp4_rouge",10],
	["shounka_mp4_violet",10],
	["shounka_clk_bleufonce",10],
	["shounka_clk_grise",10],
	["shounka_clk_jaune",10],
	["shounka_clk_noir",10],
	["shounka_clk_orange",10],
	["shounka_clk_rose",10],
	["shounka_clk_rouge",10],
	["shounka_clk_violet",10],
	["cg_jeep_blinde_noir",10],
	["cg_jeep_blinde_violet",10],
	["cg_jeep_blinde_rose",10],
	["cg_jeep_blinde_orange",10],
	["cg_jeep_blinde_grise",10],
	["cg_jeep_blinde_vert",10],
	["cg_jeep_blinde_bleufonce",10],
	["cg_jeep_blinde_bleu",10],
	["cg_jeep_blinde_white",10],
	["cg_jeep_blinde_jaune",10],
	["cg_lancer_evo_x_noir",10],
	["cg_lancer_evo_x_violet",10],
	["cg_lancer_evo_x_rose",10],
	["cg_lancer_evo_x_orange",10],
	["cg_lancer_evo_x_grise",10],
	["cg_lancer_evo_x_vert",10],
	["cg_lancer_evo_x_bleufonce",10],
	["cg_lancer_evo_x_bleu",10],
	["cg_lancer_evo_x_white",10],
	["cg_lancer_evo_x_jaune",10],
	["Mrshounka_pagani_c_bleufonce",10],
	["Mrshounka_pagani_c_grise",10],
	["Mrshounka_pagani_c_jaune",10],
	["Mrshounka_pagani_c_noir",10],
	["Mrshounka_pagani_c_orange",10],
	["Mrshounka_pagani_c_rose",10],
	["Mrshounka_pagani_c_rouge",10],
	["Mrshounka_pagani_c_violet",10],
	["cg_lambo_veneno_noir",10],
	["cg_lambo_veneno_violet",10],
	["cg_lambo_veneno_rose",10],
	["cg_lambo_veneno_orange",10],
	["cg_lambo_veneno_grise",10],
	["cg_lambo_veneno_vert",10],
	["cg_lambo_veneno_bleufonce",10],
	["cg_lambo_veneno_bleu",10],
	["cg_lambo_veneno_white",10],
	["cg_lambo_veneno_jaune",10],
	//Holden racing
	["AM_Holden_RBlue",10],			
	["AM_Holden_RRed",10],
	["AM_Holden_RWhite",10],
	["AM_Holden_RBlack",10],	
	["A3L_Veyron_purple",10],
	["A3L_Veyron_orange",10],
	["A3L_Veyron_red",10],
	["A3L_Veyron_black",10],
	["A3L_Veyron_white",10],
	["A3L_Veyron",10],
	["Mrshounka_lykan_c_bleufonce",10],
	["Mrshounka_lykan_c_grise",10],
	["Mrshounka_lykan_c_jaune",10],
	["Mrshounka_lykan_c_noir",10],
	["Mrshounka_lykan_c_orange",10],
	["Mrshounka_lykan_c_rose",10],
	["Mrshounka_lykan_c_rouge",10],
	["Mrshounka_lykan_c_violet",10],
	["A3L_Ferrari458red",10],
	["A3L_Ferrari458black",10],
	["A3L_Ferrari458white",10],
	["A3L_Ferrari458blue",10],
	["shounka_f430_spider_bleufonce",10],
	["shounka_f430_spider_grise",10],
	["shounka_f430_spider_jaune",10],
	["shounka_f430_spider_noir",10],
	["shounka_f430_spider_orange",10],
	["shounka_f430_spider_rose",10],
	["shounka_f430_spider_rouge",10],
	["shounka_f430_spider_violet",10],
	["shounka_porsche911_bleufonce",10],
	["shounka_porsche911_grise",10],
	["shounka_porsche911_jaune",10],
	["shounka_porsche911_noir",10],
	["shounka_porsche911_orange",10],
	["shounka_porsche911_rose",10],
	["shounka_porsche911_rouge",10],
	["shounka_porsche911_violet",10],
	["CG_Lamborghini_Aventador_Red",10],
	["CG_Lamborghini_Aventador_Black",10],
	["CG_Lamborghini_Aventador_Blue",10],
	["CG_Lamborghini_Aventador_Green",10],
	["CG_Lamborghini_Aventador_Orange",10],
	["CG_Lamborghini_Aventador_Purple",10],
	["CG_Lamborghini_Aventador_White",10],
	["A3L_EvoXrally_green",10],
	["A3L_EvoXrally_white",10],
	["A3L_EvoXrally_red",10],
	["A3L_EvoXrally_blue",10],
	 //chev_car
	["DAR_TahoeCivSilver",10],
	["DAR_TahoeCivBlue",10],
	["DAR_TahoeCivRed",10],
	["DAR_TahoeCivBlack",10],
	["A3L_SuburbanWhite",10],
	["A3L_SuburbanBlue",10],
	["A3L_SuburbanRed",10],
	["A3L_SuburbanBlack",10],
	["A3L_SuburbanGrey",10],
	["A3L_SuburbanOrange",10],
	["A3L_Camaro",10],
	//ford_car
	["cg_raptor_truck_noir",10],
	["cg_raptor_truck_violet",10],
	["cg_raptor_truck_rose",10],
	["cg_raptor_truck_orange",10],
	["cg_raptor_truck_grise",10],
	["cg_raptor_truck_vert",10],
	["cg_raptor_truck_bleufonce",10],
	["cg_raptor_truck_bleu",10],
	["cg_raptor_truck_white",10],
	["cg_raptor_truck_jaune",10],
	["cg_raptor_truck_va_noir",10],
	["cg_raptor_truck_va_violet",10],
	["cg_raptor_truck_va_rose",10],
	["cg_raptor_truck_va_orange",10],
	["cg_raptor_truck_va_grise",10],
	["cg_raptor_truck_va_vert",10],
	["cg_raptor_truck_va_bleufonce",10],
	["cg_raptor_truck_va_bleu",10],
	["cg_raptor_truck_va_white",10],
	["cg_raptor_truck_va_jaune",10],
	["cg_ford_mustang_noir",10],
	["cg_ford_mustang_violet",10],
	["cg_ford_mustang_rose",10],
	["cg_ford_mustang_orange",10],
	["cg_ford_mustang_grise",10],
	["cg_ford_mustang_vert",10],
	["cg_ford_mustang_bleufonce",10],
	["cg_ford_mustang_bleu",10],
	["cg_ford_mustang_white",10],
	["cg_ford_mustang_jaune",10],
	["cg_ford_mustang_rouge",10],
	//dodge_car
	["AM_2015C_Black",10],
	["AM_2015C_blue",10],
	["AM_2015C_white",10],
	["cg_dodge_charger_2015_noir",10],
	["cg_dodge_charger_2015_violet",10],
	["cg_dodge_charger_2015_rose",10],
	["cg_dodge_charger_2015_orange",10],
	["cg_dodge_charger_2015_grise",10],
	["cg_dodge_charger_2015_vert",10],
	["cg_dodge_charger_2015_bleufonce",10],
	["cg_dodge_charger_2015_bleu",10],
	["cg_dodge_charger_2015_white",10],
   ["cg_dodge_charger_2015_jaune",10],
   ["cg_dodge_charger_2015_rouge",10],
   ["A3L_ChallengerWhite",10],
   ["A3L_ChallengerRed",10],
   ["A3L_ChallengerBlack",10],
   ["A3L_ChallengerBlue",10],
   ["A3L_ChallengerGreen",10],
   ["A3L_Challenger",10],
	//civ_car
	["CG_Taxi",10],
	["critgamin_smart_civ",10],
	["critgamin_smart_bleu",10],
	["critgamin_smart_noir",10],
	["critgamin_smart_bleufonce",10],
	["critgamin_smart_rouge",10],
	["critgamin_smart_jaune",10],
	["critgamin_smart_rose",10],
	["critgamin_smart_grise",10],
	["critgamin_smart_violet",10],
	["critgamin_smart_orange",10],
	["critgamin_smart_vert",10],
	["critgamin_contown_civ",10],
	["critgamin_contown_bleu",10],
	["critgamin_contown_noir",10],
	["critgamin_contown_bleufonce",10],
	["critgamin_contown_rouge",10],
	["critgamin_contown_jaune",10],
	["critgamin_contown_rose",10],
	["critgamin_contown_grise",10],
	["critgamin_contown_violet",10],
	["critgamin_contown_jaune",10],
	["critgamin_contown_orange",10],			
	["critgamin_contown_vert",10],
	["critgamin_vangmcc_civ_noir",10],
	["critgamin_vangmcc_civ_bleufonce",10],
	["critgamin_vangmcc_civ_bleu",10],
	["critgamin_vangmcc_civ_vert",10],
	["critgamin_vangmcc_civ_rouge",10],
	["critgamin_vangmcc_civ_jaune",10],
	["critgamin_vangmcc_civ_rose",10],
	["critgamin_vangmcc_civ_grise",10],
	["critgamin_vangmcc_civ_violet",10],
	["critgamin_vangmcc_civ_orange",10],
	["cg_mercedes_sprint_van_noir",10],
	["cg_mercedes_sprint_van_violet",10],
	["cg_mercedes_sprint_van_rose",10],
	["cg_mercedes_sprint_van_orange",10],
	["cg_mercedes_sprint_van_grise",10],
	["cg_mercedes_sprint_van_vert",10],
	["cg_mercedes_sprint_van_bleufonce",10],
	["cg_mercedes_sprint_van_bleu",10],
	["cg_mercedes_sprint_van_white",10],
	["cg_mercedes_sprint_van_jaune",10],
	["cg_mercedes_sprint_van_rouge",10],
	["cg_citroen_c4_noir",10],
	["cg_citroen_c4_violet",10],
	["cg_citroen_c4_rose",10],
	["cg_citroen_c4_orange",10],
	["cg_citroen_c4_grise",10],
	["cg_citroen_c4_vert",10],
	["cg_citroen_c4_bleufonce",10],
	["cg_citroen_c4_bleu",10],
	["cg_citroen_c4_white",10],
	["cg_citroen_c4_jaune",10],
	["cg_citroen_c4_rouge",10],
	["cg_renault_twingo_noir",10],
	["cg_renault_twingo_violet",10],
	["cg_renault_twingo_rose",10],
	["cg_renault_twingo_orange",10],
	["cg_renault_twingo_grise",10],
	["cg_renault_twingo_vert",10],
	["cg_renault_twingo_bleufonce",10],
	["cg_renault_twingo_bleu",10],
	["cg_renault_twingo_white",10],
	["cg_renault_twingo_jaune",10],
	["cg_renault_twingo_rouge",10],
	["cg_citroen_ds3_noir",10],
	["cg_citroen_ds3_violet",10],
	["cg_citroen_ds3_rose",10],
	["cg_citroen_ds3_orange",10],
	["cg_citroen_ds3_grise",10],
	["cg_citroen_ds3_vert",10],
	["cg_citroen_ds3_bleufonce",10],
	["cg_citroen_ds3_bleu",10],
	["cg_citroen_ds3_white",10],
	["cg_citroen_ds3_jaune",10],
	["cg_citroen_ds3_rouge",10],
	["cg_citroen_ds4_noir",10],
	["cg_citroen_ds4_violet",10],
	["cg_citroen_ds4_rose",10],
	["cg_citroen_ds4_orange",10],
	["cg_citroen_ds4_grise",10],
	["cg_citroen_ds4_vert",10],
	["cg_citroen_ds4_bleufonce",10],
	["cg_citroen_ds4_bleu",10],
	["cg_citroen_ds4_white",10],
	["cg_citroen_ds4_jaune",10],
	["cg_citroen_ds4_rouge",10],
	["cg_peugeot_308_gti_civ_noir",10],
	["cg_peugeot_308_gti_civ_violet",10],
	["cg_peugeot_308_gti_civ_rose",10],
	["cg_peugeot_308_gti_civ_orange",10],
	["cg_peugeot_308_gti_civ_grise",10],
	["cg_peugeot_308_gti_civ_vert",10],
	["cg_peugeot_308_gti_civ_bleufonce",10],
	["cg_peugeot_308_gti_civ_bleu",10],
	["cg_peugeot_308_gti_civ_white",10],
	["cg_peugeot_308_gti_civ_jaune",10],
	["cg_peugeot_308_gti_civ_rouge",10],
	["cg_peugeot_308_rcz_noir",10],
	["cg_peugeot_308_rcz_violet",10],
	["cg_peugeot_308_rcz_rose",10],
	["cg_peugeot_308_rcz_orange",10],
	["cg_peugeot_308_rcz_grise",10],
	["cg_peugeot_308_rcz_vert",10],
	["cg_peugeot_308_rcz_bleufonce",10],
	["cg_peugeot_308_rcz_bleu",10],
	["cg_peugeot_308_rcz_white",10],
	["cg_peugeot_308_rcz_jaune",10],
	["cg_peugeot_308_rcz_rouge",10],
	["Mrshounka_Alfa_Romeo_bleufonce",10],
	["Mrshounka_Alfa_Romeo_grise",10],
	["Mrshounka_Alfa_Romeo_jaune",10],
	["Mrshounka_Alfa_Romeo_noir",10],
	["Mrshounka_Alfa_Romeo_orange",10],
	["Mrshounka_Alfa_Romeo_rose",10],
	["Mrshounka_Alfa_Romeo_rouge",10],
	["Mrshounka_Alfa_Romeo_violet",10],
	["S_Rangerover_Black",10],
	["S_Rangerover_Red",10],
	["S_Rangerover_Blue",10],
	["S_Rangerover_Green",10],
	["S_Rangerover_Purple",10],
	["S_Rangerover_Grey",10],
	["S_Rangerover_Orange",10],
	["S_Rangerover_White",10],
	["POP_Qashqai_amarillo",10],
	["pop_toyota_gt86_Blanco",10],
	["pop_toyota_gt86_silver",10],
	["pop_toyota_gt86_gris",10],
	["pop_toyota_gt86_negro",10],
	["pop_toyota_gt86_azul",10],
	["pop_toyota_gt86_rojo",10],
	["cg_peugeot_508_civ_noir",10],
	["cg_peugeot_508_civ_violet",10],
	["cg_peugeot_508_civ_rose",10],
	["cg_peugeot_508_civ_orange",10],
	["cg_peugeot_508_civ_grise",10],
	["cg_peugeot_508_civ_vert",10],
	["cg_peugeot_508_civ_bleufonce",10],
	["cg_peugeot_508_civ_bleu",10],
	["cg_peugeot_508_civ_white",10],
	["cg_peugeot_508_civ_jaune",10],
	["cg_peugeot_508_civ_rouge",10],
	["A3L_JeepGrayBlack",10],
	["A3L_JeepGrayTan",10],
	["A3L_JeepTanTan",10],
	["A3L_JeepTanBlack",10],
	["A3L_JeepRedBlack",10],
	["A3L_JeepRedTan",10],
	["A3L_JeepGreenBlack",10],
	["A3L_JeepGreenTan",10],
	["A3L_JeepWhiteBlack",10],
	["A3L_Jeep",10],
	["shounka_transam_orange",10],
	["shounka_transam_violet",10],
	["shounka_transam_grise",10],
	["shounka_transam_rose",10],
	["shounka_transam_jaune",10],
	["shounka_transam_rouge",10],
	["shounka_transam_bleufonce",10],
	["shounka_transam_noir",10],
	["shounka_transam",10],
	//civ_motorbike
	["tcg_hrly",10],
	["tcg_hrly_white",10],	
	["tcg_hrly_red",10],
	["tcg_hrly_metal",10],
	["tcg_hrly_blue",10],
	["tcg_hrly_limited",10],
	["tcg_hrly_demon",10],
	["tcg_hrly_coco",10],
	["tcg_hrly_orig1",10],
	["tcg_hrly_orig2",10],
	["tcg_hrly_skeleton",10],
	["tcg_hrly_gay",10],
	["cg_ducati_civ_noir",10],
	["cg_ducati_civ_violet",10],
	["cg_ducati_civ_rose",10],
	["cg_ducati_civ_orange",10],
	["cg_ducati_civ_grise",10],
	["cg_ducati_civ_vert",10],
	["cg_ducati_civ_bleufonce",10],
	["cg_ducati_civ_bleu",10],
	["cg_ducati_civ_white",10],
	["cg_ducati_civ_jaune",10],
	["cg_ducati_civ_rouge",10],
	 //civ_truck
	["Jonzie_Transit",10],
	["C_Van_01_fuel_F",10],
	["C_Van_01_box_F",10],
	["C_Van_01_transport_F",10],
	["shounka_nemo_bleufonce",10],
	["shounka_nemo_grise",10],
	["shounka_nemo_jaune",10],
	["shounka_nemo_noir",10],
	["shounka_nemo_orange",10],
	["shounka_nemo_rose",10],
	["shounka_nemo_rouge",10],
	["shounka_nemo_violet",10],
	["cg_hummer_h1_noir",10],
	["cg_hummer_h1_violet",10],
	["cg_hummer_h1_rose",10],
	["cg_hummer_h1_orange",10],
	["cg_hummer_h1_grise",10],
	["cg_hummer_h1_vert",10],
	["cg_hummer_h1_bleufonce",10],
	["cg_hummer_h1_bleu",10],
	["cg_hummer_h1_white",10],
	["cg_hummer_h1_jaune",10],
	["shounka_h2_bleufonce",10],
	["shounka_h2_grise",10],
	["shounka_h2_jaune",10],
	["shounka_h2_noir",10],
	["shounka_h2_orange",10],
	["shounka_h2_rose",10],
	["shounka_h2_rouge",10],
	["shounka_h2_violet",10],
	["A3L_Bus",10],
	["pop_bus_p",10],
	["cg_daf_xf_euro6_noir",10],
	["cg_daf_xf_euro6_violet",10],
	["cg_daf_xf_euro6_rose",10],
	["cg_daf_xf_euro6_orange",10],
	["cg_daf_xf_euro6_grise",10],
	["cg_daf_xf_euro6_vert",10],
	["cg_daf_xf_euro6_bleufonce",10],
	["cg_daf_xf_euro6_white",10],
	["cg_daf_xf_euro6_jaune",10],
	["cg_daf_xf_euro6_rouge",10],
	["Jonzie_Flat_Bed",10],
	["Jonzie_Log_Truck",10],
	["Jonzie_Box_Truck",10],
	["Jonzie_Tanker_Truck",10],
	["cg_renault_magnum_truck_f_noir",10],
	["cg_renault_magnum_truck_f_violet",10],
	["cg_renault_magnum_truck_f_rose",10],
	["cg_renault_magnum_truck_f_orange",10],
	["cg_renault_magnum_truck_f_grise",10],
	["cg_renault_magnum_truck_f_vert",10],
	["cg_renault_magnum_truck_f_white",10],
	["cg_renault_magnum_truck_f_jaune",10],
	["shounka_avalanche_bleufonce",10],
	["shounka_avalanche_grise",10],
	["shounka_avalanche_jaune",10],
	["shounka_avalanche_noir",10],
	["shounka_avalanche_orange",10],
	["shounka_avalanche_rose",10],
	["shounka_avalanche_rouge",10],
	["shounka_avalanche_violet",10],
	["shounka_ivceco_bleufonce",10],
	["shounka_ivceco_grise",10],
	["shounka_ivceco_jaune",10],
	["shounka_ivceco_noir",10],
	["shounka_ivceco_orange",10],
	["shounka_ivceco_rose",10],
	["shounka_ivceco_rouge",10],
	["shounka_ivceco_violet",10],
	["Nhz_audia8limo",10],
	["cg_audi_a8_limo_noir",10],
	["cg_audi_a8_limo_violet",10],
	["cg_audi_a8_limo_rose",10],
	["cg_audi_a8_limo_orange",10],
	["cg_audi_a8_limo_grise",10],
	["cg_audi_a8_limo_vert",10],
	["cg_audi_a8_limo_bleufonce",10],
	["cg_audi_a8_limo_bleu",10],
	["cg_audi_a8_limo_white",10],
	["cg_audi_a8_limo_jaune",10],
	["wirk_h3_limo",10],
	 //reb_car
	["B_Quadbike_01_F",10],
	["I_G_Van_01_fuel_F",10],
	["B_Heli_Light_01_F",10],
	["B_G_Offroad_01_F",10],
	["O_Heli_Light_02_unarmed_F",10],
	 //cop_car
	["ivory_wrx_marked",10],
	["ivory_wrx_unmarked",10],
	["ivory_wrx_slicktop",10],
	["ivory_isf_unmarked",10],
	["ivory_isf_slicktop",10],
	["ivory_m3_unmarked",10],
	["ivory_m3_slicktop",10],
	["A3L_CVPIFPBDOC",10],
	["A3L_TaurusCO2",10],
	["cg_cvpifpblbpd",10],	
	["cg_TaurusPD1",10],	
	["DAR_ExplorerPolice",10],
	["charger_pd_skinned",10],
	["cg_ss2",10],
	["DAR_ExplorerSheriff",10],
	["charger_sh_skinned",10],			
	["cg_suburban_sert_pol",10],					
	["cg_evoSERT1",10],
	["charger_sert",10],
	["cg_h2_sert",10],	
	["AM_Holden_SO",10],		
	["A3L_CVPIUC",10],
	["A3L_CVPIUCBlack",10],
	["A3L_CVPIUCBlue",10],
	["cg_mercedes_sprinter_pol_base_reg",10],
	["cg_ducati_pol_reg",10],			
	["DAR_ExplorerPoliceStealth",10],			
	["A3L_jailBus",10],
	 //civ_air
	["B_Heli_Light_01_F",10],
	["ivory_b206",10],
	["ivory_b206_news",10],
	["CUP_C_DC3_CIV",10],
	["CUP_C_C47_CIV",10],			
	["GNT_C185",10],
	["IVORY_CRJ200_1",10],
	["IVORY_ERJ135_1",10],
	 //cop_air	
	["B_Heli_Light_01_F",10],
	["C_Heli_Light_01_civil_F",10],
	["EC635_SAR",10],
	["EC635_PRPG_SERT",10],
	["melb_h6m",10],
	["B_Heli_Light_01_F",10],
	["EC635_SAR",10],
	["EC635_PRPG_SERT",10],
	["C_Heli_Light_01_civil_F",10],
	["EC635_prpg_lvsf",10],
	["Urbanized_LaFerrari_red",10],
	["Urbanized_LaFerrari_black",10],
	["Urbanized_LaFerrari_white",10],
	["Urbanized_LaFerrari_blue",10],
	["Urbanized_LaFerrari_purple",10],
	["Urbanized_LaFerrari_pink",10],
	["Urbanized_LaFerrari_orange",10],
	["Urbanized_LaFerrari_darkred",10],
	["Urbanized_LaFerrari_hotpink",10],
	["Urbanized_LaFerrari_yellow",10],
	["Urbanized_LaFerrari_lime",10],
	["Urbanized_LaFerrari_Blue_Special",10],
	["Urbanized_LaFerrari_Lime_Special",10],
	["EC635_prpg_presidental",10]
];
__CONST__(life_impound_prices,life_impound_prices);

life_garage_sell =
[
			["ivory_wrx_cop_marked",9000],
			["ivory_wrx_cop_unmarked",9000],
			["ivory_wrx_cop_slicktop",9000],
			["cg_evoblack",9000],

			//DOC
			["cg_evocor1",9000],
			["A3L_SuburbanDOC",9000],
			["charger_cor_skinned",9000],
			
			//PD
			["cg_cvpifpbpd",9000],
			["cg_TaurusPD2",9000],
			["cg_evopol1",9000],
			["charger_pd",9000],
			["charger_pd_skinned",9000],
			
			//SO
			["cg_CVPISH",9000],
			["cg_TaurusSS1",9000],
			["cg_TaurusSS2",9000],
			["cg_evoss1",9000],
			["charger_sh",9000],
			["charger_sh_skinned",9000],			

			//ST
			["cg_cvpitrooper",9000],
			["cg_taurustrooperf",9000],		
			["cg_trooperevo",9000],
			["charger_st",9000],
			["charger_trp_skinned",9000],			
			
			//SERT					
			["AM_Holden_UM",9000],

			["EC635_prpg_lvsf",20000],
			["EC635_prpg_presidental",20000],
			["ADM_General_Lee",20000],
             //MaxRacing
			["IVORY_PRIUS",3750],
			["ivory_supra",4500],
			["ivory_supra_tuned",30000],
			["ivory_isf",6000],
			["ivory_m3",7500],
			["ivory_m3_gts",16500],
			["ivory_wrx",27000],
			["ivory_lp560",63900],
			["IVORY_R8",24900],
			["IVORY_R8SPYDER",21900],
			["IVORY_REV",20700],	
			["ivory_lfa",41700],
			["ivory_c",37800],
			["ivory_gt500",24000],
             //showroom_car
			["Jonzie_Quattroporte",45000],
			["Jonzie_30CSL",9000],
			["Jonzie_Viper",13500],
			["Jonzie_Datsun_Z432",15000],
			["Jonzie_STI",21900],
			["Jonzie_Escalade",12000],
			["Jonzie_Datsun_510",6000],
			["Jonzie_Ceed",2250],
			["Jonzie_Raptor",12000],
			["Jonzie_Galant",1500],
			["Jonzie_Corolla",1050],
			["Jonzie_Mini_Cooper",300],
			["Jonzie_Mini_Cooper_R_spec",1500],
			["Jonzie_XB",9000],
			["Jonzie_VE",9000],
			["Jonzie_Ute",9000],
	         //kart_shop
			["A3L_Karts",500],
			["C_Kart_01_Blu_F",500],
			["C_Kart_01_Fuel_F",500],
			["C_Kart_01_Red_F",500],
			["C_Kart_01_Vrana_F",500],
	         //exo_car
			["cg_peugeot_207_rc_noir",1200],
			["cg_peugeot_207_rc_violet",1200],
			["cg_peugeot_207_rc_rose",1200],
			["cg_peugeot_207_rc_orange",1200],
			["cg_peugeot_207_rc_grise",1200],
			["cg_peugeot_207_rc_vert",1200],
			["cg_peugeot_207_rc_bleufonce",1200],
			["cg_peugeot_207_rc_bleu",1200],
			["cg_peugeot_207_rc_white",1200],
			["cg_peugeot_207_rc_jaune",1200],
			["cg_volkswagen_touareg_noir",1800],
			["cg_volkswagen_touareg_violet",1800],
			["cg_volkswagen_touareg_rose",1800],
			["cg_volkswagen_touareg_orange",1800],
			["cg_volkswagen_touareg_grise",1800],
			["cg_volkswagen_touareg_vert",1800],
			["cg_volkswagen_touareg_bleufonce",1800],
			["cg_volkswagen_touareg_bleu",1800],
			["cg_volkswagen_touareg_white",1800],
			["cg_volkswagen_touareg_jaune",1800],
			["cg_vw_golfvi_noir",1800],
			["cg_vw_golfvi_violet",1800],
			["cg_vw_golfvi_rose",1800],
			["cg_vw_golfvi_orange",1800],
			["cg_vw_golfvi_grise",1800],
			["cg_vw_golfvi_vert",1800],
			["cg_vw_golfvi_bleufonce",1800],
			["cg_vw_golfvi_bleu",1800],
			["cg_vw_golfvi_white",1800],
			["cg_vw_golfvi_jaune",1800],
			["cg_jeep_cherokee_noir",4170],
			["cg_jeep_cherokee_violet",4170],
			["cg_jeep_cherokee_rose",4170],
			["cg_jeep_cherokee_orange",4170],
			["cg_jeep_cherokee_grise",4170],
			["cg_jeep_cherokee_vert",4170],
			["cg_jeep_cherokee_bleufonce",4170],
			["cg_jeep_cherokee_bleu",4170],
			["cg_jeep_cherokee_white",4170],
			["cg_jeep_cherokee_jaune",4170],
			["cg_audi_rs4_noir",18000],
			["cg_audi_rs4_violet",18000],
			["cg_audi_rs4_rose",18000],
			["cg_audi_rs4_orange",18000],
			["cg_audi_rs4_grise",18000],
			["cg_audi_rs4_vert",18000],
			["cg_audi_rs4_bleufonce",18000],
			["cg_audi_rs4_bleu",18000],
			["cg_audi_rs4_white",18000],
			["cg_audi_rs4_jaune",18000],
			["cg_audi_rs5_noir",19500],
			["cg_audi_rs5_violet",19500],
			["cg_audi_rs5_rose",19500],
			["cg_audi_rs5_orange",19500],
			["cg_audi_rs5_grise",19500],
			["cg_audi_rs5_vert",19500],
			["cg_audi_rs5_bleufonce",19500],
			["cg_audi_rs5_bleu",19500],
			["cg_audi_rs5_white",19500],
			["cg_audi_rs5_jaune",19500],
            ["shounka_rs6_orange",21000],
            ["shounka_rs6_violet",21000],
            ["shounka_rs6_grise",21000],
            ["shounka_rs6_rose",21000],
            ["shounka_rs6_jaune",21000],
            ["shounka_rs6_rouge",21000],
            ["shounka_rs6_bleufonce",21000],
            ["shounka_rs6",21000],
            ["shounka_rs6_noir",21000],	
			["cg_bmw_1series_m_noir",8700],
			["cg_bmw_1series_m_violet",8700],
			["cg_bmw_1series_m_rose",8700],
			["cg_bmw_1series_m_orange",8700],
			["cg_bmw_1series_m_grise",8700],
			["cg_bmw_1series_m_vert",8700],
			["cg_bmw_1series_m_bleufonce",8700],
			["cg_bmw_1series_m_bleu",8700],
			["cg_bmw_1series_m_white",8700],
			["cg_bmw_1series_m_jaune",8700],
			["cg_bmw_m6_noir",11700],
			["cg_bmw_m6_violet",11700],
			["cg_bmw_m6_rose",11700],
			["cg_bmw_m6_orange",11700],
			["cg_bmw_m6_bleufonce",11700],
			["cg_bmw_m6_bleu",11700],
			["cg_bmw_m6_white",11700],
			["cg_bmw_m6_jaune",11700],						
            ["A3L_BMW135Red",6600],
            ["A3L_BMW135Purple",6600],
            ["A3L_BMW135Blue",6600],
            ["A3L_BMW135Black",6600],
            ["A3L_BMW135White",6600],
            ["A3L_BMW135Sport5",6600],
            ["A3L_BMW135Sport4",6600],
            ["A3L_BMW135Sport3",6600],
            ["A3L_BMW135Sport2",6600],
            ["A3L_BMW135Sport1",6600], 			
			["cg_renault_megane_rs_2015_noir",11700],
			["cg_renault_megane_rs_2015_violet",11700],
			["cg_renault_megane_rs_2015_rose",11700],
			["cg_renault_megane_rs_2015_orange",11700],
			["cg_renault_megane_rs_2015_grise",11700],
			["cg_renault_megane_rs_2015_vert",11700],
			["cg_renault_megane_rs_2015_bleufonce",11700],
			["cg_renault_megane_rs_2015_bleu",11700],
			["cg_renault_megane_rs_2015_white",11700],
			["cg_renault_megane_rs_2015_jaune",11700],
			["Mrshounka_c63_2015_bleufonce",11400],
			["Mrshounka_c63_2015_grise",11400],
			["Mrshounka_c63_2015_jaune",11400],
			["Mrshounka_c63_2015_noir",11400],
			["Mrshounka_c63_2015_orange",11400],
			["Mrshounka_c63_2015_rose",11400],
			["Mrshounka_c63_2015_rouge",11400],
			["Mrshounka_c63_2015_violet",11400],
			["cg_raptor_truck_noir",11700],
			["cg_raptor_truck_violet",11700],
			["cg_raptor_truck_rose",11700],
			["cg_raptor_truck_orange",11700],
			["cg_raptor_truck_grise",11700],
			["cg_raptor_truck_vert",11700],
			["cg_raptor_truck_bleufonce",11700],
			["cg_raptor_truck_bleu",11700],
			["cg_raptor_truck_white",11700],
			["cg_raptor_truck_jaune",11700],
			["cg_porsche_911_82_noir",14700],
			["cg_porsche_911_82_violet",14700],
			["cg_porsche_911_82_rose",14700],
			["cg_porsche_911_82_orange",14700],
			["cg_porsche_911_82_grise",14700],
			["cg_porsche_911_82_vert",14700],
			["cg_porsche_911_82_bleufonce",14700],
			["cg_porsche_911_82_bleu",14700],
			["cg_porsche_911_82_white",14700],
			["cg_porsche_911_82_jaune",14700],
			["cg_porsche_cayenne_noir",14700],
			["cg_porsche_cayenne_violet",14700],
			["cg_porsche_cayenne_rose",14700],
			["cg_porsche_cayenne_orange",14700],
			["cg_porsche_cayenne_grise",14700],
			["cg_porsche_cayenne_vert",14700],
			["cg_porsche_cayenne_bleufonce",14700],
			["cg_porsche_cayenne_bleu",14700],
			["cg_porsche_cayenne_white",14700],
			["cg_porsche_cayenne_jaune",14700],
			["cg_bowler_offroad_noir",14700],
			["cg_bowler_offroad_violet",14700],
			["cg_bowler_offroad_rose",14700],
			["cg_bowler_offroad_orange",14700],
			["cg_bowler_offroad_grise",14700],
			["cg_bowler_offroad_vert",14700],
			["cg_bowler_offroad_bleufonce",14700],
			["cg_bowler_offroad_bleu",14700],
			["cg_bowler_offroad_white",14700],
			["cg_bowler_offroad_jaune",14700],
			["Mrshounka_agera_p_noir",147000],
			["Mrshounka_agera_p_bleu",147000],
			["Mrshounka_agera_p_jaune",147000],			
			["shounka_gt_bleufonce",18000],
			["shounka_gt_grise",18000],
			["shounka_gt_jaune",18000],
			["shounka_gt_noir",18000],
			["shounka_gt_orange",18000],
			["shounka_gt_rose",18000],
			["shounka_gt_rouge",18000],
			["shounka_gt_violet",18000],
			["Mrshounka_mercedes_190_p_bleufonce",18600],
			["Mrshounka_mercedes_190_p_grise",18600],
			["Mrshounka_mercedes_190_p_jaune",18600],
			["Mrshounka_mercedes_190_p_noir",18600],
			["Mrshounka_mercedes_190_p_orange",18600],
			["Mrshounka_mercedes_190_p_rose",18600],
			["Mrshounka_mercedes_190_p_rouge",18600],
			["Mrshounka_mercedes_190_p_violet",18600],
			//HOLDENS
			["AM_Holden_White",23550],
			["AM_Holden_Black",23550],
			["AM_Holden_Green",23550],
			["AM_Holden_DarkGreen",23550],
			["AM_Holden_OffGreen",23550],
			["AM_Holden_blue",23550],
			["AM_Holden_OffYellow",23550],
			["AM_Holden_Pink",23550],
			["AM_Holden_Purple",23550],
			["AM_Holden_Yellow",23550],
			["cg_nissan_gtr_2012_noir",23700],
			["cg_nissan_gtr_2012_violet",23700],
			["cg_nissan_gtr_2012_rose",23700],
			["cg_nissan_gtr_2012_orange",23700],
			["cg_nissan_gtr_2012_grise",23700],
			["cg_nissan_gtr_2012_vert",23700],
			["cg_nissan_gtr_2012_bleufonce",23700],
			["cg_nissan_gtr_2012_bleu",23700],
			["cg_nissan_gtr_2012_white",23700],
			["cg_nissan_gtr_2012_jaune",23700],		
			["shounka_mp4_bleufonce",33300],
			["shounka_mp4_grise",33300],
			["shounka_mp4_jaune",33300],
			["shounka_mp4_noir",33300],
			["shounka_mp4_orange",33300],
			["shounka_mp4_rose",33300],
			["shounka_mp4_rouge",33300],
			["shounka_mp4_violet",33300],
			["shounka_clk_bleufonce",33300],
			["shounka_clk_grise",33300],
			["shounka_clk_jaune",33300],
			["shounka_clk_noir",33300],
			["shounka_clk_orange",33300],
			["shounka_clk_rose",33300],
			["shounka_clk_rouge",33300],
			["shounka_clk_violet",33300],
			["cg_jeep_blinde_noir",41700],
			["cg_jeep_blinde_violet",41700],
			["cg_jeep_blinde_rose",41700],
			["cg_jeep_blinde_orange",41700],
			["cg_jeep_blinde_grise",41700],
			["cg_jeep_blinde_vert",41700],
			["cg_jeep_blinde_bleufonce",41700],
			["cg_jeep_blinde_bleu",41700],
			["cg_jeep_blinde_white",41700],
			["cg_jeep_blinde_jaune",41700],
			["cg_lancer_evo_x_noir",47700],
			["cg_lancer_evo_x_violet",47700],
			["cg_lancer_evo_x_rose",47700],
			["cg_lancer_evo_x_orange",47700],
			["cg_lancer_evo_x_grise",47700],
			["cg_lancer_evo_x_vert",47700],
			["cg_lancer_evo_x_bleufonce",47700],
			["cg_lancer_evo_x_bleu",47700],
			["cg_lancer_evo_x_white",47700],
			["cg_lancer_evo_x_jaune",47700],
			["Mrshounka_pagani_c_bleufonce",47700],
			["Mrshounka_pagani_c_grise",47700],
			["Mrshounka_pagani_c_jaune",47700],
			["Mrshounka_pagani_c_noir",47700],
			["Mrshounka_pagani_c_orange",47700],
			["Mrshounka_pagani_c_rose",47700],
			["Mrshounka_pagani_c_rouge",47700],
			["Mrshounka_pagani_c_violet",47700],
			["cg_lambo_veneno_noir",47700],
			["cg_lambo_veneno_violet",47700],
			["cg_lambo_veneno_rose",47700],
			["cg_lambo_veneno_orange",47700],
			["cg_lambo_veneno_grise",47700],
			["cg_lambo_veneno_vert",47700],
			["cg_lambo_veneno_bleufonce",47700],
			["cg_lambo_veneno_bleu",47700],
			["cg_lambo_veneno_white",47700],
			["cg_lambo_veneno_jaune",47700],
			//Holden racing
			["AM_Holden_RBlue",59550],			
			["AM_Holden_RRed",59550],
			["AM_Holden_RWhite",59550],
			["AM_Holden_RBlack",59550],	
			["A3L_Veyron_purple",63000],
            ["A3L_Veyron_orange",63000],
            ["A3L_Veyron_red",63000],
            ["A3L_Veyron_black",63000],
            ["A3L_Veyron_white",63000],
            ["A3L_Veyron",63000],
			["Mrshounka_lykan_c_bleufonce",60000],
			["Mrshounka_lykan_c_grise",60000],
			["Mrshounka_lykan_c_jaune",60000],
			["Mrshounka_lykan_c_noir",60000],
			["Mrshounka_lykan_c_orange",60000],
			["Mrshounka_lykan_c_rose",60000],
			["Mrshounka_lykan_c_rouge",60000],
			["Mrshounka_lykan_c_violet",60000],
			["A3L_Ferrari458red",67500],
            ["A3L_Ferrari458black",67500],
            ["A3L_Ferrari458white",67500],
            ["A3L_Ferrari458blue",67500],
			["shounka_f430_spider_bleufonce",66000],
			["shounka_f430_spider_grise",66000],
			["shounka_f430_spider_jaune",66000],
			["shounka_f430_spider_noir",66000],
			["shounka_f430_spider_orange",66000],
			["shounka_f430_spider_rose",66000],
			["shounka_f430_spider_rouge",66000],
			["shounka_f430_spider_violet",66000],
			["shounka_porsche911_bleufonce",69000],
			["shounka_porsche911_grise",69000],
			["shounka_porsche911_jaune",69000],
			["shounka_porsche911_noir",69000],
			["shounka_porsche911_orange",69000],
			["shounka_porsche911_rose",69000],
			["shounka_porsche911_rouge",69000],
			["shounka_porsche911_violet",69000],
			["CG_Lamborghini_Aventador_Red", 90000],
			["CG_Lamborghini_Aventador_Black", 90000],
			["CG_Lamborghini_Aventador_Blue", 90000],
			["CG_Lamborghini_Aventador_Green", 90000],
			["CG_Lamborghini_Aventador_Orange", 90000],
			["CG_Lamborghini_Aventador_Purple", 90000],
			["CG_Lamborghini_Aventador_White", 90000],
			["A3L_EvoXrally_green",100000],
			["A3L_EvoXrally_white",100000],
			["A3L_EvoXrally_red",100000],
			["A3L_EvoXrally_blue",100000],
             //chev_car
			["DAR_TahoeCivSilver",4200],
			["DAR_TahoeCivBlue",4200],
			["DAR_TahoeCivRed",4200],
			["DAR_TahoeCivBlack",4200],
			["A3L_SuburbanWhite",5700],
			["A3L_SuburbanBlue",5700],
			["A3L_SuburbanRed",5700],
			["A3L_SuburbanBlack",5700],
			["A3L_SuburbanGrey",5700],
			["A3L_SuburbanOrange",5700],
			["A3L_Camaro",5850],
	        //ford_car
			["cg_raptor_truck_noir",11700],
			["cg_raptor_truck_violet",11700],
			["cg_raptor_truck_rose",11700],
			["cg_raptor_truck_orange",11700],
			["cg_raptor_truck_grise",11700],
			["cg_raptor_truck_vert",11700],
			["cg_raptor_truck_bleufonce",11700],
			["cg_raptor_truck_bleu",11700],
			["cg_raptor_truck_white",11700],
			["cg_raptor_truck_jaune",11700],
			["cg_raptor_truck_va_noir",11700],
			["cg_raptor_truck_va_violet",11700],
			["cg_raptor_truck_va_rose",11700],
			["cg_raptor_truck_va_orange",11700],
			["cg_raptor_truck_va_grise",11700],
			["cg_raptor_truck_va_vert",11700],
			["cg_raptor_truck_va_bleufonce",11700],
			["cg_raptor_truck_va_bleu",11700],
			["cg_raptor_truck_va_white",11700],
			["cg_raptor_truck_va_jaune",11700],
			["cg_ford_mustang_noir",16770],
			["cg_ford_mustang_violet",16770],
			["cg_ford_mustang_rose",16770],
			["cg_ford_mustang_orange",16770],
			["cg_ford_mustang_grise",16770],
			["cg_ford_mustang_vert",16770],
			["cg_ford_mustang_bleufonce",16770],
			["cg_ford_mustang_bleu",16770],
			["cg_ford_mustang_white",16770],
			["cg_ford_mustang_jaune",16770],
			["cg_ford_mustang_rouge",16770],
	        //dodge_car
			["AM_2015C_Black",6300],
			["AM_2015C_blue",6300],
			["AM_2015C_white",6300],
			["cg_dodge_charger_2015_noir",7770],
			["cg_dodge_charger_2015_violet",7770],
			["cg_dodge_charger_2015_rose",7770],
			["cg_dodge_charger_2015_orange",7770],
			["cg_dodge_charger_2015_grise",7770],
			["cg_dodge_charger_2015_vert",7770],
			["cg_dodge_charger_2015_bleufonce",7770],
			["cg_dodge_charger_2015_bleu",7770],
			["cg_dodge_charger_2015_white",7770],
		   ["cg_dodge_charger_2015_jaune",7770],
		   ["cg_dodge_charger_2015_rouge",7770],
           ["A3L_ChallengerWhite",9000],
           ["A3L_ChallengerRed",9000],
           ["A3L_ChallengerBlack",9000],
           ["A3L_ChallengerBlue",9000],
           ["A3L_ChallengerGreen",9000],
           ["A3L_Challenger",9000],
            //civ_car
			["CG_Taxi",333],
	     	["critgamin_smart_civ",333],
			["critgamin_smart_bleu",540],
			["critgamin_smart_noir",540],
			["critgamin_smart_bleufonce",540],
			["critgamin_smart_rouge",540],
			["critgamin_smart_jaune",540],
			["critgamin_smart_rose",540],
			["critgamin_smart_grise",540],
			["critgamin_smart_violet",540],
			["critgamin_smart_orange",540],
			["critgamin_smart_vert",540],
			["critgamin_contown_civ",540],
			["critgamin_contown_bleu",540],
			["critgamin_contown_noir",540],
			["critgamin_contown_bleufonce",540],
			["critgamin_contown_rouge",540],
			["critgamin_contown_jaune",540],
			["critgamin_contown_rose",540],
			["critgamin_contown_grise",540],
			["critgamin_contown_violet",540],
			["critgamin_contown_jaune",540],
			["critgamin_contown_orange",540],			
			["critgamin_contown_vert",540],
			["critgamin_vangmcc_civ_noir",540],
			["critgamin_vangmcc_civ_bleufonce",540],
			["critgamin_vangmcc_civ_bleu",540],
			["critgamin_vangmcc_civ_vert",540],
			["critgamin_vangmcc_civ_rouge",540],
			["critgamin_vangmcc_civ_jaune",540],
			["critgamin_vangmcc_civ_rose",540],
			["critgamin_vangmcc_civ_grise",540],
			["critgamin_vangmcc_civ_violet",540],
			["critgamin_vangmcc_civ_orange",540],
			["cg_mercedes_sprint_van_noir",750],
			["cg_mercedes_sprint_van_violet",750],
			["cg_mercedes_sprint_van_rose",750],
			["cg_mercedes_sprint_van_orange",750],
			["cg_mercedes_sprint_van_grise",750],
			["cg_mercedes_sprint_van_vert",750],
			["cg_mercedes_sprint_van_bleufonce",750],
			["cg_mercedes_sprint_van_bleu",750],
			["cg_mercedes_sprint_van_white",750],
			["cg_mercedes_sprint_van_jaune",750],
			["cg_mercedes_sprint_van_rouge",750],
			["cg_citroen_c4_noir",1470],
			["cg_citroen_c4_violet",1470],
			["cg_citroen_c4_rose",1470],
			["cg_citroen_c4_orange",1470],
			["cg_citroen_c4_grise",1470],
			["cg_citroen_c4_vert",1470],
			["cg_citroen_c4_bleufonce",1470],
			["cg_citroen_c4_bleu",1470],
			["cg_citroen_c4_white",1470],
			["cg_citroen_c4_jaune",1470],
			["cg_citroen_c4_rouge",1470],
			["cg_renault_twingo_noir",1470],
			["cg_renault_twingo_violet",1470],
			["cg_renault_twingo_rose",1470],
			["cg_renault_twingo_orange",1470],
			["cg_renault_twingo_grise",1470],
			["cg_renault_twingo_vert",1470],
			["cg_renault_twingo_bleufonce",1470],
			["cg_renault_twingo_bleu",1470],
			["cg_renault_twingo_white",1470],
			["cg_renault_twingo_jaune",1470],
			["cg_renault_twingo_rouge",1470],
			["cg_citroen_ds3_noir",1470],
			["cg_citroen_ds3_violet",1470],
			["cg_citroen_ds3_rose",1470],
			["cg_citroen_ds3_orange",1470],
			["cg_citroen_ds3_grise",1470],
			["cg_citroen_ds3_vert",1470],
			["cg_citroen_ds3_bleufonce",1470],
			["cg_citroen_ds3_bleu",1470],
			["cg_citroen_ds3_white",1470],
			["cg_citroen_ds3_jaune",1470],
			["cg_citroen_ds3_rouge",1470],
			["cg_citroen_ds4_noir",1770],
			["cg_citroen_ds4_violet",1770],
			["cg_citroen_ds4_rose",1770],
			["cg_citroen_ds4_orange",1770],
			["cg_citroen_ds4_grise",1770],
			["cg_citroen_ds4_vert",1770],
			["cg_citroen_ds4_bleufonce",1770],
			["cg_citroen_ds4_bleu",1770],
			["cg_citroen_ds4_white",1770],
			["cg_citroen_ds4_jaune",1770],
			["cg_citroen_ds4_rouge",1770],
			["cg_peugeot_308_gti_civ_noir",1770],
			["cg_peugeot_308_gti_civ_violet",1770],
			["cg_peugeot_308_gti_civ_rose",1770],
			["cg_peugeot_308_gti_civ_orange",1770],
			["cg_peugeot_308_gti_civ_grise",1770],
			["cg_peugeot_308_gti_civ_vert",1770],
			["cg_peugeot_308_gti_civ_bleufonce",1770],
			["cg_peugeot_308_gti_civ_bleu",1770],
			["cg_peugeot_308_gti_civ_white",1770],
			["cg_peugeot_308_gti_civ_jaune",1770],
			["cg_peugeot_308_gti_civ_rouge",1770],
			["cg_peugeot_308_rcz_noir",1770],
			["cg_peugeot_308_rcz_violet",1770],
			["cg_peugeot_308_rcz_rose",1770],
			["cg_peugeot_308_rcz_orange",1770],
			["cg_peugeot_308_rcz_grise",1770],
			["cg_peugeot_308_rcz_vert",1770],
			["cg_peugeot_308_rcz_bleufonce",1770],
			["cg_peugeot_308_rcz_bleu",1770],
			["cg_peugeot_308_rcz_white",1770],
			["cg_peugeot_308_rcz_jaune",1770],
			["cg_peugeot_308_rcz_rouge",1770],
			["Mrshounka_Alfa_Romeo_bleufonce",2550],
			["Mrshounka_Alfa_Romeo_grise",2550],
			["Mrshounka_Alfa_Romeo_jaune",2550],
			["Mrshounka_Alfa_Romeo_noir",2550],
			["Mrshounka_Alfa_Romeo_orange",2550],
			["Mrshounka_Alfa_Romeo_rose",2550],
			["Mrshounka_Alfa_Romeo_rouge",2550],
			["Mrshounka_Alfa_Romeo_violet",2550],
			["S_Rangerover_Black",2550],
			["S_Rangerover_Red",2550],
			["S_Rangerover_Blue",2550],
			["S_Rangerover_Green",2550],
			["S_Rangerover_Purple",2550],
			["S_Rangerover_Grey",2550],
			["S_Rangerover_Orange",2550],
			["S_Rangerover_White",2550],
			["POP_Qashqai_amarillo",2550],
			["pop_toyota_gt86_Blanco",2550],
			["pop_toyota_gt86_silver",2550],
            ["pop_toyota_gt86_gris",2550],
            ["pop_toyota_gt86_negro",2550],
            ["pop_toyota_gt86_azul",2550],
            ["pop_toyota_gt86_rojo",2550],
			["cg_peugeot_508_civ_noir",4770],
			["cg_peugeot_508_civ_violet",4770],
			["cg_peugeot_508_civ_rose",4770],
			["cg_peugeot_508_civ_orange",4770],
			["cg_peugeot_508_civ_grise",4770],
			["cg_peugeot_508_civ_vert",4770],
			["cg_peugeot_508_civ_bleufonce",4770],
			["cg_peugeot_508_civ_bleu",4770],
			["cg_peugeot_508_civ_white",4770],
			["cg_peugeot_508_civ_jaune",4770],
			["cg_peugeot_508_civ_rouge",4770],
			["A3L_JeepGrayBlack",5700],
            ["A3L_JeepGrayTan",5700],
            ["A3L_JeepTanTan",5700],
            ["A3L_JeepTanBlack",5700],
            ["A3L_JeepRedBlack",5700],
            ["A3L_JeepRedTan",5700],
            ["A3L_JeepGreenBlack",5700],
            ["A3L_JeepGreenTan",5700],
            ["A3L_JeepWhiteBlack",5700],
            ["A3L_Jeep",5700],
			["shounka_transam_orange",12000],
            ["shounka_transam_violet",12000],
            ["shounka_transam_grise",12000],
            ["shounka_transam_rose",12000],
            ["shounka_transam_jaune",12000],
            ["shounka_transam_rouge",12000],
            ["shounka_transam_bleufonce",12000],
            ["shounka_transam_noir",12000],
            ["shounka_transam",12000],
	        //civ_motorbike
			["tcg_hrly",750],
			["tcg_hrly_white",750],	
			["tcg_hrly_red",750],
			["tcg_hrly_metal",750],
			["tcg_hrly_blue",750],
			["tcg_hrly_limited",750],
			["tcg_hrly_demon",750],
			["tcg_hrly_coco",750],
			["tcg_hrly_orig1",750],
			["tcg_hrly_orig2",750],
			["tcg_hrly_skeleton",1650],
			["tcg_hrly_gay",1950],
			["cg_ducati_civ_noir",4770],
			["cg_ducati_civ_violet",4770],
			["cg_ducati_civ_rose",4770],
			["cg_ducati_civ_orange",4770],
			["cg_ducati_civ_grise",4770],
			["cg_ducati_civ_vert",4770],
			["cg_ducati_civ_bleufonce",4770],
			["cg_ducati_civ_bleu",4770],
			["cg_ducati_civ_white",4770],
			["cg_ducati_civ_jaune",4770],
			["cg_ducati_civ_rouge",4770],
	         //civ_truck
			["Jonzie_Transit",750],
			["C_Van_01_fuel_F",2100],
			["C_Van_01_box_F",2700],
			["C_Van_01_transport_F",2250],
			["shounka_nemo_bleufonce",2250],
			["shounka_nemo_grise",2250],
			["shounka_nemo_jaune",2250],
			["shounka_nemo_noir",2250],
			["shounka_nemo_orange",2250],
			["shounka_nemo_rose",2250],
			["shounka_nemo_rouge",2250],
			["shounka_nemo_violet",2250],
			["cg_hummer_h1_noir",5700],
			["cg_hummer_h1_violet",5700],
			["cg_hummer_h1_rose",5700],
			["cg_hummer_h1_orange",5700],
			["cg_hummer_h1_grise",5700],
			["cg_hummer_h1_vert",5700],
			["cg_hummer_h1_bleufonce",5700],
			["cg_hummer_h1_bleu",5700],
			["cg_hummer_h1_white",5700],
			["cg_hummer_h1_jaune",5700],
			["shounka_h2_bleufonce",6300],
			["shounka_h2_grise",6300],
			["shounka_h2_jaune",6300],
			["shounka_h2_noir",6300],
			["shounka_h2_orange",6300],
			["shounka_h2_rose",6300],
			["shounka_h2_rouge",6300],
			["shounka_h2_violet",6300],
			["A3L_Bus",3900],
			["pop_bus_p",3900],
			["cg_daf_xf_euro6_noir",7770],
			["cg_daf_xf_euro6_violet",7770],
			["cg_daf_xf_euro6_rose",7770],
			["cg_daf_xf_euro6_orange",7770],
			["cg_daf_xf_euro6_grise",7770],
			["cg_daf_xf_euro6_vert",7770],
			["cg_daf_xf_euro6_bleufonce",7770],
			["cg_daf_xf_euro6_white",7770],
			["cg_daf_xf_euro6_jaune",7770],
			["cg_daf_xf_euro6_rouge",7770],
			["Jonzie_Flat_Bed",7770],
			["Jonzie_Log_Truck",7770],
			["Jonzie_Box_Truck",7770],
			["Jonzie_Tanker_Truck",7770],
			["cg_renault_magnum_truck_f_noir",13770],
			["cg_renault_magnum_truck_f_violet",13770],
			["cg_renault_magnum_truck_f_rose",13770],
			["cg_renault_magnum_truck_f_orange",13770],
			["cg_renault_magnum_truck_f_grise",13770],
			["cg_renault_magnum_truck_f_vert",13770],
			["cg_renault_magnum_truck_f_white",13770],
			["cg_renault_magnum_truck_f_jaune",13770],
			["shounka_avalanche_bleufonce",21000],
			["shounka_avalanche_grise",21000],
			["shounka_avalanche_jaune",21000],
			["shounka_avalanche_noir",21000],
			["shounka_avalanche_orange",21000],
			["shounka_avalanche_rose",21000],
			["shounka_avalanche_rouge",21000],
			["shounka_avalanche_violet",21000],
			["shounka_ivceco_bleufonce",30000],
			["shounka_ivceco_grise",30000],
			["shounka_ivceco_jaune",30000],
			["shounka_ivceco_noir",30000],
			["shounka_ivceco_orange",30000],
			["shounka_ivceco_rose",30000],
			["shounka_ivceco_rouge",30000],
			["shounka_ivceco_violet",30000],
			["Nhz_audia8limo",9900],
			["cg_audi_a8_limo_noir",35700],
			["cg_audi_a8_limo_violet",35700],
			["cg_audi_a8_limo_rose",35700],
			["cg_audi_a8_limo_orange",35700],
			["cg_audi_a8_limo_grise",35700],
			["cg_audi_a8_limo_vert",35700],
			["cg_audi_a8_limo_bleufonce",35700],
			["cg_audi_a8_limo_bleu",35700],
			["cg_audi_a8_limo_white",35700],
			["cg_audi_a8_limo_jaune",35700],
			["wirk_h3_limo",123900],
			["Urbanized_LaFerrari_red",280000],
			["Urbanized_LaFerrari_black",280000],
			["Urbanized_LaFerrari_white",280000],
			["Urbanized_LaFerrari_blue",280000],
			["Urbanized_LaFerrari_purple",280000],
			["Urbanized_LaFerrari_pink",280000],
			["Urbanized_LaFerrari_orange",280000],
			["Urbanized_LaFerrari_darkred",280000],
			["Urbanized_LaFerrari_hotpink",280000],
			["Urbanized_LaFerrari_yellow",280000],
			["Urbanized_LaFerrari_lime",280000],
			["Urbanized_LaFerrari_Blue_Special",360000],
			["Urbanized_LaFerrari_Lime_Special",360000],
	         //reb_car
			["B_Quadbike_01_F",150],
			["I_G_Van_01_fuel_F",4200],
			["B_Heli_Light_01_F",21000],
			["B_G_Offroad_01_F",4950],
			["O_Heli_Light_02_unarmed_F",75000],
	         //cop_car
			["ivory_wrx_marked",600],
			["ivory_wrx_unmarked",600],
			["ivory_wrx_slicktop",600],
			["ivory_isf_unmarked",600],
			["ivory_isf_slicktop",600],
			["ivory_m3_unmarked",600],
			["ivory_m3_slicktop",600],
			["A3L_CVPIFPBDOC",600],
			["A3L_TaurusCO2",750],
			["cg_cvpifpblbpd",600],	
			["cg_TaurusPD1",750],	
			["DAR_ExplorerPolice",1200],
			["charger_pd_skinned",2700],
			["cg_ss2",750],
			["DAR_ExplorerSheriff",1200],
			["charger_sh_skinned",2700],			
			["cg_suburban_sert_pol",1200],					
			["cg_evoSERT1",2100],
			["charger_sert",2700],
			["cg_h2_sert",3300],	
			["AM_Holden_SO",1200],		
			["A3L_CVPIUC",600],
			["A3L_CVPIUCBlack",600],
			["A3L_CVPIUCBlue",600],
			["cg_mercedes_sprinter_pol_base_reg",750],
			["cg_ducati_pol_reg",750],			
			["DAR_ExplorerPoliceStealth",900],			
			["A3L_jailBus",1500],
	         //civ_air
			["B_Heli_Light_01_F",10500],
			["ivory_b206",10500],
			["ivory_b206_news",12000],
			["CUP_C_DC3_CIV",24000],
			["CUP_C_C47_CIV",30000],			
			["GNT_C185",30000],
			["IVORY_CRJ200_1",30000],
			["IVORY_ERJ135_1",30000],
             //cop_air	
			["B_Heli_Light_01_F",1350],
			["C_Heli_Light_01_civil_F",1350],
			["EC635_SAR",600],
			["EC635_PRPG_SERT",600],
			["melb_h6m",2550],
			["B_Heli_Light_01_F",1350],
			["EC635_SAR",600],
			["EC635_PRPG_SERT",600],
			["C_Heli_Light_01_civil_F",1350],
			
			// Medic Cars
			["cg_ambulanceexpansion",10],
			["A3L_TowTruck_ADAC",10],
			["RR_Firetruck",10],
			["DAR_TahoeEMS",10],
			["pop_grua",10],
			["A3L_CVPILBFD",10],
			["cg_evoems1",10],
			["cg_evoems2",10],
			["cg_evoems3",10],
			["AM_Holden_RFA",10]

];
__CONST__(life_garage_sell,life_garage_sell);
